add_source_term_residue – FEST-3D
add_source_term_residue Subroutine
41 statements
Source File
public subroutine add_source_term_residue(qp, residue, cells, Ifaces, Jfaces, Kfaces, scheme, flow, dims)
Call to add different source terms to the residual of different equations.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-2:dims%imx+2, -2:dims%jmx+2, -2:dims%kmx+2, 1:dims%n_var) :: qp
Store primitive variable at cell center
real(kind=wp), intent(inout), dimension(:, :, :, :) :: residue
Store residue at each cell-center
type(celltype), intent(in), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2) :: cells
Input cell quantities: volume
type(facetype), intent(in), dimension(-2:dims%imx+3,-2:dims%jmx+2,-2:dims%kmx+2) :: Ifaces
Input varaible which stores I faces' area and unit normal
type(facetype), intent(in), dimension(-2:dims%imx+2,-2:dims%jmx+3,-2:dims%kmx+2) :: Jfaces
Input varaible which stores J faces' area and unit normal
type(facetype), intent(in), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+3) :: Kfaces
Input varaible which stores K faces' area and unit normal
type(schemetype), intent(in) :: scheme
finite-volume Schemes
type(flowtype), intent(in) :: flow
Information about fluid flow: freestream-speed, ref-viscosity,etc.
type(extent), intent(in) :: dims
Extent of the domain:imx,jmx,kmx
Calls
Called by
Contents
Source Code
add_source_term_residue
Source Code
    subroutine add_source_term_residue(qp, residue, cells, Ifaces,Jfaces,Kfaces,scheme,flow, dims)
      !< Call to add different source terms to the residual of different equations.
      implicit none
      type(schemetype), intent(in) :: scheme
      !< finite-volume Schemes
      type(flowtype), intent(in) :: flow
      !< Information about fluid flow: freestream-speed, ref-viscosity,etc.
      type(extent), intent(in) :: dims
      !< Extent of the domain:imx,jmx,kmx
      real(wp), dimension(-2:dims%imx+2, -2:dims%jmx+2, -2:dims%kmx+2, 1:dims%n_var), intent(in) :: qp
      !< Store primitive variable at cell center
      real(wp), dimension(:, :, :, :), intent(inout)  :: residue
      !< Store residue at each cell-center
      type(celltype), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2), intent(in) :: cells
      !< Input cell quantities: volume
      type(facetype), dimension(-2:dims%imx+3,-2:dims%jmx+2,-2:dims%kmx+2), intent(in) :: Ifaces
      !< Input varaible which stores I faces' area and unit normal
      type(facetype), dimension(-2:dims%imx+2,-2:dims%jmx+3,-2:dims%kmx+2), intent(in) :: Jfaces
      !< Input varaible which stores J faces' area and unit normal
      type(facetype), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+3), intent(in) :: Kfaces
      !< Input varaible which stores K faces' area and unit normal
      DebugCall('add_source_term_residue')
      select case (trim(scheme%turbulence))
        case ('none')
          !do nothing
          continue
        case ('sa')
          select case(trim(scheme%transition))
            case('none')
              call add_sa_source(qp, residue, cells, Ifaces,Jfaces,Kfaces,dims)
            case('bc')
              call add_saBC_source(qp, residue, cells, Ifaces,Jfaces,Kfaces,flow, dims)
            case DEFAULT
              Fatal_error
          end select
        case ('sst', 'sst2003')
          select case(trim(scheme%transition))
            case('none')
              call add_sst_source(qp, residue, cells,scheme, dims)
            case('lctm2015')
              call add_sst_source_lctm2015(qp, residue, cells,Ifaces,Jfaces,Kfaces,scheme, dims)
            case('bc')
              call add_sst_bc_source(qp, residue, cells,flow,dims)
            case DEFAULT
              Fatal_error
          end select
        case ('kkl')
          call add_kkl_source(qp, residue, cells, Ifaces,Jfaces,Kfaces, dims)
        case DEFAULT
          Fatal_error
      end select
    end subroutine add_source_term_residue
Call graph
add_source_term_residue calls add_sst_source_lctm2015, add_kkl_source, add_sst_bc_source, add_sabc_source, add_sst_source, debugcall, add_sa_source
add_sst_source_lctm2015 calls find_dccvn
find_dccvn calls compute_gradient, find_ccvn
get_total_conservative_residue calls add_source_term_residue
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step