add_sst_source_lctm2015 – FEST-3D
add_sst_source_lctm2015 Subroutine
104 statements
Source File
private subroutine add_sst_source_lctm2015()
Add residual due to source terms of the LCTM2015 transition model
Arguments
None
Calls
Called by
Contents
Source Code
add_sst_source_lctm2015
Source Code
    subroutine add_sst_source_lctm2015()
      !< Add residual due to source terms of the LCTM2015 transition model
      implicit none
      integer :: i,j,k
      real :: CD
      real :: F1
      real :: vort
      real :: S_K
      real :: S_w
      real :: S_gm
      real :: D_k
      real :: D_w
      real :: D_gm
      real :: P_k
      real :: P_w
      real :: P_gm
      real :: lamda
      real :: Fonset1
      real :: Fonset2
      real :: Fonset3
      real :: Fonset
      real :: Rev
      Real :: RT
      real :: Fturb
      real :: Re_theta
      real :: TuL
      real :: gradtk
      real :: strain
      real :: intermittency
      real :: Pk_lim
      real :: Fon_lim
      real :: dudx
      real :: dudy
      real :: dudz
      real :: duds
      real :: velmag
      real :: u,v,w
      real :: lamd
      real :: Fpg
      real :: divergence
      real :: dvdy
      integer :: limiter
      if(trim(turbulence) == 'sst2003')then
        limiter = 10
        gama1 = 5.0/9.0
        gama2 = 0.44
      else
        limiter = 20
      end if
      !for pressure gradient calculation
      call find_DCCVn()
      do k = 1,kmx-1
        do j = 1,jmx-1
          do i = 1,imx-1
            intermittency = qp(i,j,k,n_var)
            ! __ vorticity __
            vort = sqrt(     ((gradw_y(i,j,k)- gradv_z(i,j,k))**2 &
                            + (gradu_z(i,j,k)- gradw_x(i,j,k))**2 &
                            + (gradv_x(i,j,k)- gradu_y(i,j,k))**2 &
                             )&
                       )
            strain = sqrt(     (((gradw_y(i,j,k) + gradv_z(i,j,k))**2) &
                              + ((gradu_z(i,j,k) + gradw_x(i,j,k))**2) &
                              + ((gradv_x(i,j,k) + gradu_y(i,j,k))**2) &
                              + 2*(gradu_x(i,j,k)**2) &
                              + 2*(gradv_y(i,j,k)**2) &
                              + 2*(gradw_z(i,j,k)**2) &
                               )&
                         )
            CD = 2*density(i,j,k)*sigma_w2*(gradtk_x(i,j,k)*gradtw_x(i,j,k)&
                                          + gradtk_y(i,j,k)*gradtw_y(i,j,k)&
                                          + gradtk_z(i,j,k)*gradtw_z(i,j,k)&
                                           )/tw(i,j,k)
            CD = max(CD, 10.0**(-limiter))
            F1 = sst_F1(i,j,k)
            sigma_k     =    sigma_k1*F1  +    sigma_k2*(1. - F1)
            sigma_w     =    sigma_w1*F1  +    sigma_w1*(1. - F1)
            gama        =       gama1*F1  +       gama2*(1. - F1)
            beta        =       beta1*F1  +       beta2*(1. - F1)
            ! ____ Dissipation term ___
            D_k = bstar*density(i,j,k)*tw(i,j,k)*tk(i,j,k)
            D_w = beta*density(i,j,k)*tw(i,j,k)**2
            ! ____ PRODUCTION term____
            divergence = gradu_x(i,j,k) + gradv_y(i,j,k) + gradw_z(i,j,k)
            P_k = sst_mu(i,j,k)*(vort*strain) - ((2.0/3.0)*density(i,j,k)*tk(i,j,k)*divergence)
            P_k = min(P_k, limiter*D_k)
            P_w = (density(i,j,k)*gama/sst_mu(i,j,k))*P_k
            ! ____ cross diffusion term ___
            lamda = (1. - F1)*CD
            ! ____Transition modeling  ____
              ! --pressure gradient
!            u = qp(i,j,k,2)
!            v = qp(i,j,k,3)
!            w = qp(i,j,k,4)
!            velmag = sqrt((u**2) + (v**2) + (w**2))
!            dudx = 0.5*((2.0*u*gradu_x(i,j,k)) + (2.0*v*gradv_x(i,j,k)) + (2.0*w*gradw_x(i,j,k)))/velmag
!            dudy = 0.5*((2.0*u*gradu_y(i,j,k)) + (2.0*v*gradv_y(i,j,k)) + (2.0*w*gradw_y(i,j,k)))/velmag
!            dudz = 0.5*((2.0*u*gradu_z(i,j,k)) + (2.0*v*gradv_z(i,j,k)) + (2.0*w*gradw_z(i,j,k)))/velmag
!            duds = (((u/velmag)*dudx) + ((v/velmag)*dudy) + ((w/velmag)*dudz))
!            !lamd =(-7.57e-3)*(duds*dist(i,j,k)*dist(i,j,k)*density(i,j,k)/mu(i,j,k)) + 0.0128
!            lamd =(+7.57e-3)*(duds*dist(i,j,k)*dist(i,j,k)*density(i,j,k)/mu(i,j,k)) + 0.0128
            dvdy = DCCVnX(i,j,k)*CCnormalX(i,j,k) &
                 + DCCVnY(i,j,k)*CCnormalY(i,j,k) &
                 + DCCVnZ(i,j,k)*CCnormalZ(i,j,k)
            lamd =(-7.57e-3)*(dvdy*dist(i,j,k)*dist(i,j,k)*density(i,j,k)/mu(i,j,k)) + 0.0128
            lamd = min(max(lamd, -1.0), 1.0)
            if(lamd>=0.0)then
                Fpg = min(1.0 + 14.68*lamd, 1.5)
            else
                Fpg = min(1.0 - 7.34*lamd, 3.0)
            end if
            Fpg = max(Fpg, 0.0)
              ! --gradient
            TuL = min(100.0*sqrt(2.0*tk(i,j,k)/3.0)/(tw(i,j,k)*dist(i,j,k)),100.0)
            Re_theta = 100.0 + 1000.0*exp(-TuL*Fpg)
            !Re_theta = 100.0 + 1000.0*exp(-TuL)
            Rev = density(i,j,k)*dist(i,j,k)*dist(i,j,k)*strain/mu(i,j,k)
            RT = density(i,j,k)*tk(i,j,k)/(mu(i,j,k)*tw(i,j,k))
            Fturb = exp(-(0.5*Rt)**4)
            Fonset1 = Rev/(2.2*Re_theta)
            Fonset2 = min(Fonset1, 2.0)
            Fonset3 = max(1.0 - (RT/3.5)**3, 0.0)
            Fonset  = max(Fonset2 - Fonset3, 0.0)
            P_gm = 100*density(i,j,k)*strain*intermittency*(1.0 - intermittency)*Fonset
            D_gm = 0.06*density(i,j,k)*vort*intermittency*Fturb*((50.0*intermittency) - 1.0)
            Fon_lim = min(max((Rev/(2.2*1100.0))-1.0, 0.0), 3.0)
            Pk_lim = 5*max(intermittency - 0.2,0.0)*(1.0 - intermittency)*Fon_lim*max(3*mu(i,j,k) - mu_t(i,j,k), 0.0)*strain*vort
            S_k = intermittency*P_k - max(intermittency,0.1)*D_k  +  Pk_lim      !Source term gm
            S_W = P_w - D_w  + lamda        !Source term gm
            S_gm = P_gm - D_gm           !Source term gm
            S_k = S_k * volume(i, j, k)
            S_w = S_w * volume(i, j, k)
            S_gm= S_gm* Volume(i, j, k)
            TKE_residue(i, j, k)   = TKE_residue(i, j, k) - S_k
            omega_residue(i, j, k) = omega_residue(i, j, k) - S_w
            residue(i,j,k,n_var) = residue(i,j,k,n_var) -S_gm
          end do
        end do
      end do
    end subroutine add_sst_source_lctm2015
Call graph
add_sst_source_lctm2015 calls find_dccvn
find_dccvn calls compute_gradient, find_ccvn
add_source_term_residue calls add_sst_source_lctm2015
get_total_conservative_residue calls add_source_term_residue
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step