add_sa_source – FEST-3D
add_sa_source Subroutine
70 statements
Source File
private subroutine add_sa_source()
Add residual due to source terms of SA turbulence model
Arguments
None
Called by
Contents
Source Code
add_sa_source
Source Code
    subroutine add_sa_source()
      !< Add residual due to source terms of SA turbulence model
      implicit none
      integer :: i,j,k
      real :: CD1
      real :: CD2
      real :: fv1
      real :: fv2
      real :: fw
      real :: g
      real :: Scap
      real :: r
      real :: vort
      real :: S_v
      real :: D_v
      real :: P_v
      real :: lamda
      real :: kd2
      real :: xi
      real :: nu
      real :: gradrho_x
      real :: gradrho_y
      real :: gradrho_z
      real, dimension(6) :: RhoFace
      real, dimension(6) :: Area
      real, dimension(6,3) :: Normal
      do k = 1,kmx-1
        do j = 1,jmx-1
          do i = 1,imx-1
            RhoFace(1) = density(i-1,j  ,k  )+density(i,j,k)
            RhoFace(2) = density(i  ,j-1,k  )+density(i,j,k)
            RhoFace(3) = density(i  ,j  ,k-1)+density(i,j,k)
            RhoFace(4) = density(i+1,j  ,k  )+density(i,j,k)
            RhoFace(5) = density(i  ,j+1,k  )+density(i,j,k)
            RhoFace(6) = density(i  ,j  ,k+1)+density(i,j,k)
            Area(1) = xA(i,j,k)
            Area(2) = yA(i,j,k)
            Area(3) = zA(i,j,k)
            Area(4) = xA(i+1,j  ,k  )
            Area(5) = yA(i  ,j+1,k  )
            Area(6) = zA(i  ,j  ,k+1)
            Normal(1,1:3) = xn(i,j,k,:)
            Normal(2,1:3) = yn(i,j,k,:)
            Normal(3,1:3) = zn(i,j,k,:)
            Normal(4,1:3) = xn(i+1,j  ,k  ,:)
            Normal(5,1:3) = yn(i  ,j+1,k  ,:)
            Normal(6,1:3) = zn(i  ,j  ,k+1,:)
            gradrho_x = (-(RhoFace(1))*Normal(1,1)*Area(1) &
                         -(RhoFace(2))*Normal(2,1)*Area(2) &
                         -(RhoFace(3))*Normal(3,1)*Area(3) &
                         +(RhoFace(4))*Normal(4,1)*Area(4) &
                         +(RhoFace(5))*Normal(5,1)*Area(5) &
                         +(RhoFace(6))*Normal(6,1)*Area(6) &
                        )/(2*volume(i,j,k))
            gradrho_y = (-(RhoFace(1))*Normal(1,2)*Area(1) &
                         -(RhoFace(2))*Normal(2,2)*Area(2) &
                         -(RhoFace(3))*Normal(3,2)*Area(3) &
                         +(RhoFace(4))*Normal(4,2)*Area(4) &
                         +(RhoFace(5))*Normal(5,2)*Area(5) &
                         +(RhoFace(6))*Normal(6,2)*Area(6) &
                        )/(2*volume(i,j,k))
            gradrho_z = (-(RhoFace(1))*Normal(1,3)*Area(1) &
                         -(RhoFace(2))*Normal(2,3)*Area(2) &
                         -(RhoFace(3))*Normal(3,3)*Area(3) &
                         +(RhoFace(4))*Normal(4,3)*Area(4) &
                         +(RhoFace(5))*Normal(5,3)*Area(5) &
                         +(RhoFace(6))*Normal(6,3)*Area(6) &
                        )/(2*volume(i,j,k))
            ! __ vorticity __
            vort = sqrt(  ((gradw_y(i,j,k)- gradv_z(i,j,k))**2 &
                         + (gradu_z(i,j,k)- gradw_x(i,j,k))**2 &
                         + (gradv_x(i,j,k)- gradu_y(i,j,k))**2 &
                          )&
                       )
            ! ___ cross diffusion ___
            CD1 = cb2*((gradtv_x(i,j,k)*gradtv_x(i,j,k))&
                    +  (gradtv_y(i,j,k)*gradtv_y(i,j,k))&
                    +  (gradtv_z(i,j,k)*gradtv_z(i,j,k))&
                     )
            ! ___ addition cross diffusion result conservative form of tv ___
            CD2 =    ((gradrho_x*gradtv_x(i,j,k))&
                    + (gradrho_y*gradtv_y(i,j,k))&
                    + (gradrho_z*gradtv_z(i,j,k))&
                     )
            kd2  = (kappa_sa*dist(i,j,k))**2
            nu   = mu(i,j,k)/density(i,j,k)
            xi   = tv(i,j,k)/nu
            ! ___ functions ___
            fv1  = (xi**3)/((xi**3) + (cv1**3))
            fv2  = 1.0 - xi/(1.0 + (xi*fv1))
            ! ___ Shear stress for production ___
            scap = max(vort + (tv(i,j,k)*fv2/(kd2)), 0.3*vort)
            ! ___ wall function ___
            r    = min(tv(i,j,k)/(Scap*kd2), 10.0)
            g    = r + cw2*((r**6) - r)
            fw   = g*( (1.0+(cw3**6))/((g**6)+(cw3**6)) )**(1.0/6.0)
            ! ____ Dissipation term ___
            D_v = density(i,j,k)*cw1*fw*((tv(i,j,k)/dist(i,j,k))**2)
            ! ____ PRODUCTION term____
            P_v = density(i,j,k)*cb1*Scap*tv(i,j,k)
            ! ____ cross diffusion term ___
            lamda = density(i,j,k)*CD1/sigma_sa - CD2*(nu+tv(i,j,k))/sigma_sa
            S_v = (P_v - D_v  + lamda)*volume(i,j,k)
            tv_residue(i, j, k)   = tv_residue(i, j, k) - S_v
          end do
        end do
      end do
    end subroutine add_sa_source
Call graph
add_source_term_residue calls add_sa_source
get_total_conservative_residue calls add_source_term_residue
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step