allocate_memory_volumes – FEST-3D
allocate_memory_volumes Subroutine
4 statements
Source File
private subroutine allocate_memory_volumes()
Allocate memory for the volume variables.
Arguments
None
Calls
Called by
Contents
Source Code
allocate_memory_volumes
Source Code
        subroutine allocate_memory_volumes()
            !< Allocate memory for the volume variables.
            !-----------------------------------------------------------
            implicit none
            call alloc(volume, -2, imx+2, -2, jmx+2, -2, kmx+2, &
                    errmsg='Error: Unable to allocate memory for volume.')
        end subroutine allocate_memory_volumes
Call graph
allocate_memory_volumes calls alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
allocate_memory calls allocate_memory_volumes
setup_geometry calls allocate_memory
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run