allocate_memory – FEST-3D
allocate_memory Subroutine
6 statements
Source File
private subroutine allocate_memory()
Allocate memory to the state variables
Arguments
None
Calls
Called by
Contents
Source Code
allocate_memory
Source Code
        subroutine allocate_memory()
            !< Allocate memory to the state variables
            !-----------------------------------------------------------
            implicit none
            DebugCall("allocate_memory")
            ! The state of the system is defined by the primitive
            ! variables (density, velocity and pressure) at the grid
            ! cell centers.
            call alloc(qp, -2, imx+2, -2, jmx+2, -2, kmx+2, 1, n_var, AErrMsg("qp"))
            call alloc(qp_inf, 1, n_var, AErrMsg("qp_inf"))
        end subroutine allocate_memory
Call graph
allocate_memory calls alloc, debugcall, aerrmsg
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_state calls allocate_memory
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run