alloc_rank3_real – FEST-3D
alloc_rank3_real Subroutine
18 statements
Source File
private subroutine alloc_rank3_real(var, start1, stop1, start2, stop2, start3, stop3, errmsg)
Allcoate 3-Dimensional array of type: real
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:, :, :), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
integer, intent(in) :: start3
Starting index of Var array's dimension
integer, intent(in) :: stop3
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
Called by
Contents
None
Call graph
alloc calls alloc_rank3_real
setup_scheme calls alloc
allocate_memory_normals calls alloc
destroy_time calls alloc
setup_time calls alloc
setup_plusgs calls alloc
allocate_memory calls alloc, allocate_memory_normals, allocate_memory_ghost_centroids, allocate_memory_volumes, allocate_memory_areas
allocate_memory_ghost_centroids calls alloc
allocate_memory_volumes calls alloc
find_wall_dist calls alloc
setup_wall_dist calls alloc
setup_lusgs calls alloc
allocate_memory_areas calls alloc
setup_interface calls alloc
setup_bc calls alloc
setup_viscosity calls alloc
setup_update calls alloc, setup_plusgs, setup_lusgs
setup_solver calls setup_time, find_wall_dist, setup_wall_dist, setup_interface, setup_bc, setup_viscosity, setup_update, setup_resnorm, setup_grid, setup_geometry, write_surfnode
setup_all calls setup_time, find_wall_dist, setup_wall_dist, setup_bc, setup_grid, setup_geometry, write_surfnode
destroy_all calls destroy_time
setup_resnorm calls allocate_memory
destroy_solver calls destroy_time
setup_surface calls allocate_memory
setup_grid calls allocate_memory
finish_run calls destroy_solver
setup_geometry calls allocate_memory
abort_run calls destroy_solver
write_surfnode calls setup_surface
start_run calls setup_solver
main calls finish_run, start_run