allocate_memory_ghost_centroids – FEST-3D
allocate_memory_ghost_centroids Subroutine
4 statements
Source File
private subroutine allocate_memory_ghost_centroids()
Allocate memory for centroids of ghost cells
Arguments
None
Calls
Called by
Contents
Source Code
allocate_memory_ghost_centroids
Source Code
        subroutine allocate_memory_ghost_centroids()
            !< Allocate memory for centroids of ghost cells
            !-----------------------------------------------------------
            implicit none
            call alloc(CellCenter, -2, imx+2, -2, jmx+2, -2, kmx+2, 1, 3, &
                    errmsg='Error: Unable to allocate memory for volume.')
!
!            call alloc(left_ghost_centroid, 1, jmx-1, 1, kmx-1, 1, 3, &
!                    errmsg='Error: Unable to allocate memory for left_ghost_centroid')
!            call alloc(right_ghost_centroid, 1, jmx-1, 1, kmx-1, 1, 3, &
!                    errmsg='Error: Unable to allocate memory for right_ghost_centroid')
!            call alloc(front_ghost_centroid, 1, imx-1, 1, kmx-1, 1, 3, &
!                    errmsg='Error: Unable to allocate memory for front_ghost_centroid')
!            call alloc(back_ghost_centroid, 1, imx-1, 1, kmx-1, 1, 3, &
!                    errmsg='Error: Unable to allocate memory for back_ghost_centroid')
!            call alloc(top_ghost_centroid, 1, imx-1, 1, jmx-1, 1, 3, &
!                    errmsg='Error: Unable to allocate memory for top_ghost_centroid')
!            call alloc(bottom_ghost_centroid, 1, imx-1, 1, jmx-1, 1, 3, &
!                    errmsg='Error: Unable to allocate memory for bottom_ghost_centroid')
        end subroutine allocate_memory_ghost_centroids
Call graph
allocate_memory_ghost_centroids calls alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
allocate_memory calls allocate_memory_ghost_centroids
setup_geometry calls allocate_memory
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run