allocate_memory – FEST-3D
allocate_memory Subroutine
8 statements
Source File
private subroutine allocate_memory()
Allocate memory for the required variables.
Arguments
None
Calls
Called by
Contents
Source Code
allocate_memory
Source Code
        subroutine allocate_memory()
            !< Allocate memory for the required variables.
            !-----------------------------------------------------------
            implicit none
            call dmsg(1, 'geometry', 'allocate_memory')
            call allocate_memory_normals()
            call allocate_memory_areas()
            call allocate_memory_volumes()
            call allocate_memory_ghost_centroids()
        end subroutine allocate_memory
Call graph
allocate_memory calls allocate_memory_areas, allocate_memory_normals, dmsg, allocate_memory_ghost_centroids, allocate_memory_volumes
allocate_memory_areas calls alloc
allocate_memory_normals calls alloc
allocate_memory_ghost_centroids calls alloc
allocate_memory_volumes calls alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_geometry calls allocate_memory
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run