allocate_memory_normals – FEST-3D
allocate_memory_normals Subroutine
15 statements
Source File
private subroutine allocate_memory_normals()
Allocate memory for the normal variables.
Arguments
None
Calls
Called by
Contents
Source Code
allocate_memory_normals
Source Code
        subroutine allocate_memory_normals()
            !< Allocate memory for the normal variables.
            !-----------------------------------------------------------
            implicit none
            call alloc(xn, -2, imx+3, -2, jmx+2, -2, kmx+2, 1,3, &
                    errmsg='Error: Unable to allocate memory for xnx.')
            call alloc(yn, -2, imx+2, -2, jmx+3, -2, kmx+2, 1,3, &
                    errmsg='Error: Unable to allocate memory for ynx.')
            call alloc(zn, -2, imx+2, -2, jmx+2, -2, kmx+3, 1,3, &
                    errmsg='Error: Unable to allocate memory for ynx.')
            xnx(-2:imx+3,-2:jmx+2,-2:kmx+2) => xn(:,:,:,1)
            xny(-2:imx+3,-2:jmx+2,-2:kmx+2) => xn(:,:,:,2)
            xnz(-2:imx+3,-2:jmx+2,-2:kmx+2) => xn(:,:,:,3)
            ynx(-2:imx+2,-2:jmx+3,-2:kmx+2) => yn(:,:,:,1)
            yny(-2:imx+2,-2:jmx+3,-2:kmx+2) => yn(:,:,:,2)
            ynz(-2:imx+2,-2:jmx+3,-2:kmx+2) => yn(:,:,:,3)
            znx(-2:imx+2,-2:jmx+2,-2:kmx+3) => zn(:,:,:,1)
            zny(-2:imx+2,-2:jmx+2,-2:kmx+3) => zn(:,:,:,2)
            znz(-2:imx+2,-2:jmx+2,-2:kmx+3) => zn(:,:,:,3)
        end subroutine allocate_memory_normals
Call graph
allocate_memory_normals calls alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
allocate_memory calls allocate_memory_normals
setup_geometry calls allocate_memory
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run