allocate_memory – FEST-3D
allocate_memory Subroutine
10 statements
Source File
private subroutine allocate_memory()
allocate memory to str and wallc variable array
Arguments
None
Calls
Called by
Contents
Source Code
allocate_memory
Source Code
    subroutine allocate_memory()
      !< allocate memory to str and wallc variable array
        implicit none
        call dmsg(1, 'wall_find', 'setup_surface')
        n_wall = -1
        n_wall =  ((jmx)*(kmx)*(NO_SLIP_flag(1)) &
                  +(jmx)*(kmx)*(NO_SLIP_flag(2)) &
                  +(kmx)*(imx)*(NO_SLIP_flag(3)) &
                  +(kmx)*(imx)*(NO_SLIP_flag(4)) &
                  +(imx)*(jmx)*(NO_SLIP_flag(5)) &
                  +(imx)*(jmx)*(NO_SLIP_flag(6)) &
                  )
        allocate(str(1:n_wall))
        call alloc(wallc, 1, n_wall, 1, 3 ,&
                  errmsg='Error: Unable to allocate memory for wallc')
        allocate(n_wall_buf(1:total_process))
        allocate(write_flag(1:total_process))
    end subroutine allocate_memory
Call graph
allocate_memory calls alloc, dmsg
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_surface calls allocate_memory
write_surfnode calls setup_surface
setup_solver calls write_surfnode
setup_all calls write_surfnode
start_run calls setup_solver
main calls start_run