check_if_value_fixed – FEST-3D
check_if_value_fixed Subroutine
24 statements
Source File
private subroutine check_if_value_fixed(model)
A Fail-check subroutine which set the freestream as the fixed value in case not specified explicitly
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: model
Called by
Contents
Source Code
check_if_value_fixed
Source Code
    subroutine check_if_value_fixed(model)
      !< A Fail-check subroutine which set the freestream
      !< as the fixed value in case not specified explicitly
      implicit none
      character(len=*), intent(in) :: model
      select case(model)
        case("none", "lctm2015")
          !do nothing
          continue
        case("sa", 'saBC')
          if(fixed_tv(face_num)==0.0)fixed_tv(face_num)=tv_inf
        case("sst", 'sst2003')
          if(fixed_tk(face_num)==0.) fixed_tk(face_num)=tk_inf
          if(fixed_tw(face_num)==0.) fixed_tw(face_num)=tw_inf
        case("kkl")
          if(fixed_tk(face_num)==0.) fixed_tk(face_num)=tk_inf
          if(fixed_tkl(face_num)==0.) fixed_tkl(face_num)=tkl_inf
        case DEFAULT
         ! call turbulence_read_error()
         Fatal_error
      end select
      select case(trim(transition))
        case('lctm2015')
          if(fixed_tgm(face_num)==0.0) fixed_tgm(face_num)=tgm_inf
        Case DEFAULT
          continue
      end select
    end subroutine check_if_value_fixed
Call graph
supersonic_inlet calls check_if_value_fixed
subsonic_inlet calls check_if_value_fixed
far_field calls check_if_value_fixed
total_pressure calls check_if_value_fixed
populate_ghost_primitive calls supersonic_inlet, subsonic_inlet, far_field, total_pressure
get_total_conservative_residue calls populate_ghost_primitive
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step