checkpoint – FEST-3D
checkpoint Subroutine
19 statements
Source File
public subroutine checkpoint(files, qp, nodes, control, scheme, dims)
Create a checkpoint dump file if the time has come
Arguments
Type Intent Optional Attributes Name
type(filetype), intent(inout) :: files
real(kind=wp), intent(in), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2, 1:dims%n_var) :: qp
type(nodetype), intent(in), dimension(-2:dims%imx+3,-2:dims%jmx+3,-2:dims%kmx+3) :: nodes
type(controltype), intent(inout) :: control
type(schemetype), intent(in) :: scheme
type(extent), intent(in) :: dims
Calls
Called by
Contents
Source Code
checkpoint
Source Code
    subroutine checkpoint(files, qp, nodes, control, scheme, dims)
      !< Create a checkpoint dump file if the time has come
      !-----------------------------------------------------------
      implicit none
      type(filetype), intent(inout) :: files
      type(extent), intent(in) :: dims
      type(controltype), intent(inout) :: control
      type(schemetype), intent(in) :: scheme
      type(nodetype), dimension(-2:dims%imx+3,-2:dims%jmx+3,-2:dims%kmx+3), intent(in) :: nodes
      real(wp), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2, 1:dims%n_var), intent(in) :: qp
      DebugCall('checkpoint')
      if (control%checkpoint_iter .ne. 0) then
          if (mod(control%current_iter, control%checkpoint_iter) == 0 &
             .or. control%current_iter == control%max_iters) then
              call make_dump_dir(control)
              call dump_data(files, qp, nodes, control, scheme, dims)
              print*, "writing data at: ", control%current_iter, control%checkpoint_iter_count
              call purge_dump_dir(control)
              control%checkpoint_iter_count = control%checkpoint_iter_count + 1
          end if
      end if
    end subroutine checkpoint
Call graph
checkpoint calls dump_data, purge_dump_dir, debugcall, make_dump_dir
dump_data calls debugcall, write_restart_log, write_file
purge_dump_dir calls remove_directory
make_dump_dir calls create_directory
write_restart_log calls write_initial_resnorm
write_file calls close_file, write_file_tec_nodal, open_file, setup_file, write_file_vtk, write_file_tec
close_file calls debugcall
open_file calls debugcall
setup_file calls debugcall
setup_solver calls checkpoint
iterate_one_more_time_step calls checkpoint
main calls iterate_one_more_time_step, start_run
start_run calls setup_solver