close_file – FEST-3D
close_file Subroutine
7 statements
Source File
public subroutine close_file(handler)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: handler
Called by
Contents
Source Code
close_file
Source Code
    subroutine close_file(handler)
      !Generalized subroutine to close single file
      implicit none
      integer, intent(in) :: handler
      logical :: ok
      inquire(handler, opened=ok)
      if(ok)  close(handler)
    end subroutine close_file
Call graph
read_output_control calls close_file, get_rw_count
get_rw_count calls close_file
close_all_files calls close_file
destroy_resnorm calls close_file
read_res_list calls close_file
open_file calls close_file
read_interface_map calls close_file
read_input_and_controls calls read_output_control, read_res_list
setup_grid calls read_interface_map
abort_run calls close_all_files, destroy_solver
finish_run calls close_all_files, destroy_solver
destroy_solver calls destroy_resnorm
setup_solver calls read_input_and_controls, setup_grid
main calls finish_run, start_run
setup_all calls read_input_and_controls, setup_grid
start_run calls setup_solver