compute_viscous_fluxes_laminar – FEST-3D
compute_viscous_fluxes_laminar Subroutine
149 statements
Source File
private subroutine compute_viscous_fluxes_laminar(F, direction)
Compute viscous fluxes for first five Navier-Stokes equation
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:, :, :, :), pointer :: F
flux array
character(len=*), intent(in) :: direction
face direction
Called by
Contents
Source Code
compute_viscous_fluxes_laminar
Source Code
    subroutine compute_viscous_fluxes_laminar(F, direction)
      !< Compute viscous fluxes for first five Navier-Stokes equation
      implicit none
      character(len=*), intent(in) :: direction !< face direction
      real, dimension(:, :, :, :), pointer, intent(inout) :: F !< flux array
      ! local variables
      real :: dudx, dudy, dudz
      real :: dvdx, dvdy, dvdz
      real :: dwdx, dwdy, dwdz
      real :: dTdx, dTdy, dTdz
      real :: normal_comp
      real :: d_LR
      real :: T_RE
      real :: T_LE
      real :: K_heat, Qx, Qy, Qz
      real :: mu_f
      real :: mut_f
      real :: total_mu
      real :: delx
      real :: dely
      real :: delz
      real :: delu
      real :: delv
      real :: delw
      real :: delT
      real :: Tau_xx
      real :: Tau_xy
      real :: Tau_xz
      real :: Tau_yx
      real :: Tau_yy
      real :: Tau_yz
      real :: Tau_zx
      real :: Tau_zy
      real :: Tau_zz
      real :: nx
      real :: ny
      real :: nz
      real :: area
      real :: uface
      real :: vface
      real :: wface
      real, dimension(:, :, :), pointer :: fA
      real, dimension(:, :, :), pointer :: fnx
      real, dimension(:, :, :), pointer :: fny
      real, dimension(:, :, :), pointer :: fnz
      integer :: i, j, k
      integer :: ii, jj, kk
      !--------------------------------------------------------------------
      ! select Direction
      !--------------------------------------------------------------------
      select case(trim(direction))
        case('x')
          ii  =  1
          jj  =  0
          kk  =  0
          fnx => xnx
          fny => xny
          fnz => xnz
          fA(-2:imx+3, -2:jmx+2, -2:kmx+2)   => xA
        case('y')
          ii  =  0
          jj  =  1
          kk  =  0
          fnx => ynx
          fny => yny
          fnz => ynz
          fA(-2:imx+2, -2:jmx+3, -2:kmx+2)   => yA
        case('z')
          ii  =  0
          jj  =  0
          kk  =  1
          fnx => znx
          fny => zny
          fnz => znz
          fA(-2:imx+2, -2:jmx+2, -2:kmx+3)   => zA
        case Default
          Fatal_error
      end select
      !---------------------------------------------------------------------
      ! Calculating the fluxes at the faces
      !--------------------------------------------------------------------
      do k = 1, kmx - 1 + kk
       do j = 1, jmx - 1 + jj
        do i = 1, imx - 1 + ii
          !--- FACE Gradients ---!
          ! Gradients at face as average of gradients at cell centres
          dudx = 0.5 * (gradu_x(i-ii, j-jj, k-kk) + gradu_x(i, j, k))
          dudy = 0.5 * (gradu_y(i-ii, j-jj, k-kk) + gradu_y(i, j, k))
          dudz = 0.5 * (gradu_z(i-ii, j-jj, k-kk) + gradu_z(i, j, k))
          dvdx = 0.5 * (gradv_x(i-ii, j-jj, k-kk) + gradv_x(i, j, k))
          dvdy = 0.5 * (gradv_y(i-ii, j-jj, k-kk) + gradv_y(i, j, k))
          dvdz = 0.5 * (gradv_z(i-ii, j-jj, k-kk) + gradv_z(i, j, k))
          dwdx = 0.5 * (gradw_x(i-ii, j-jj, k-kk) + gradw_x(i, j, k))
          dwdy = 0.5 * (gradw_y(i-ii, j-jj, k-kk) + gradw_y(i, j, k))
          dwdz = 0.5 * (gradw_z(i-ii, j-jj, k-kk) + gradw_z(i, j, k))
          dTdx = 0.5 * (gradT_x(i-ii, j-jj, k-kk) + gradT_x(i, j, k))
          dTdy = 0.5 * (gradT_y(i-ii, j-jj, k-kk) + gradT_y(i, j, k))
          dTdz = 0.5 * (gradT_z(i-ii, j-jj, k-kk) + gradT_z(i, j, k))
          !--- For ODD-EVEN coupling error ---!
          ! distance between cell center of adjacent cell for the i,j,k face
          delx = CellCenter(i, j, k, 1) - CellCenter(i-ii, j-jj, k-kk, 1)
          dely = CellCenter(i, j, k, 2) - CellCenter(i-ii, j-jj, k-kk, 2)
          delz = CellCenter(i, j, k, 3) - CellCenter(i-ii, j-jj, k-kk, 3)
          d_LR = sqrt(delx*delx + dely*dely + delz*delz)
          ! Finding the temperature of left and right element to the face i,j,k
          T_LE = pressure(i-ii, j-jj, k-kk) / (density(i-ii, j-jj, k-kk) * R_gas)
          T_RE = pressure(i, j, k) / (density(i, j, k) * R_gas)
          ! difference in state across face
          delu = x_speed(i, j, k) - x_speed(i-ii, j-jj, k-kk)
          delv = y_speed(i, j, k) - y_speed(i-ii, j-jj, k-kk)
          delw = z_speed(i, j, k) - z_speed(i-ii, j-jj, k-kk)
          delT = T_RE - T_LE
          !normal_comp   = ( delta(phi) - (grad(phi).dot.delR) )/magnitudeR
          !new grad(phi) =  grad(phi) + correction(normal_comp.dot.delR/magnitudeR)
          normal_comp = (delu - (dudx*delx + dudy*dely + dudz*delz))/d_LR
          dudx        =  dudx + (normal_comp * delx / d_LR)
          dudy        =  dudy + (normal_comp * dely / d_LR)
          dudz        =  dudz + (normal_comp * delz / d_LR)
          normal_comp = (delv - (dvdx*delx + dvdy*dely + dvdz*delz))/d_LR
          dvdx        =  dvdx + (normal_comp * delx / d_LR)
          dvdy        =  dvdy + (normal_comp * dely / d_LR)
          dvdz        =  dvdz + (normal_comp * delz / d_LR)
          normal_comp = (delw - (dwdx*delx + dwdy*dely + dwdz*delz))/d_LR
          dwdx        = dwdx + (normal_comp * delx / d_LR)
          dwdy        = dwdy + (normal_comp * dely / d_LR)
          dwdz        = dwdz + (normal_comp * delz / d_LR)
          normal_comp = (delT - (dTdx*delx + dTdy*dely + dTdz*delz))/d_LR
          dTdx        = dTdx + (normal_comp * delx / d_LR)
          dTdy        = dTdy + (normal_comp * dely / d_LR)
          dTdz        = dTdz + (normal_comp * delz / d_LR)
          !--- end of ODD-EVEN coupling correction ---!
          mu_f  = 0.5*(mu(i-ii, j-jj, k-kk) + mu(i,j,k))
          if(trim(turbulence)/='none') then
            mut_f = 0.5*(mu_t(i-ii, j-jj, k-kk) + mu_t(i, j, k))
          else
            mut_f = 0.0
          end if
          ! effective viscosity
          total_mu = mu_f + mut_f
          ! Using lambda = -2 * mu / 3
          ! diagonal terms of stress tensor
          Tau_xx = 2. * total_mu * (dudx - ((dudx + dvdy + dwdz) / 3.))
          Tau_yy = 2. * total_mu * (dvdy - ((dudx + dvdy + dwdz) / 3.))
          Tau_zz = 2. * total_mu * (dwdz - ((dudx + dvdy + dwdz) / 3.))
          ! off diagonal symmetrical part of stress tensor
          Tau_xy = total_mu * (dvdx + dudy)
          Tau_xz = total_mu * (dwdx + dudz)
          Tau_yz = total_mu * (dwdy + dvdz)
          Tau_yx = Tau_xy
          Tau_zx = Tau_xz
          Tau_zy = Tau_yz
          ! Pr: Prandtl Number and tPr: Turbulent Prandtl number
          ! Qx, Qy, Qz: Conduction fluxes
          K_heat = (mu_f/Pr + mut_f/tPr)* gm * R_gas / (gm - 1)
          Qx = K_heat*dTdx
          Qy = K_heat*dTdy
          Qz = K_heat*dTdz
          ! calling some element from memory and keep them handy for calculation
          nx    = fnx(i,j,k)
          ny    = fny(i,j,k)
          nz    = fnz(i,j,k)
          area  =  fA(i,j,k)
          uface = 0.5 * (x_speed(i-ii, j-jj, k-kk) + x_speed(i, j, k))
          vface = 0.5 * (y_speed(i-ii, j-jj, k-kk) + y_speed(i, j, k))
          wface = 0.5 * (z_speed(i-ii, j-jj, k-kk) + z_speed(i, j, k))
          ! adding viscous fluxes to stored convective flux
          F(i, j, k, 2) = F(i, j, k, 2) - ((Tau_xx*nx + Tau_xy*ny + Tau_xz*nz)*area)
          F(i, j, k, 3) = F(i, j, k, 3) - ((Tau_yx*nx + Tau_yy*ny + Tau_yz*nz)*area)
          F(i, j, k, 4) = F(i, j, k, 4) - ((Tau_zx*nx + Tau_zy*ny + Tau_zz*nz)*area)
          ! Energy flux
          ! (TijVj + Qi)ni
          F(i, j, k, 5) = F(i, j, k, 5) - (area * ( &
                          ((Tau_xx*uface + Tau_xy*vface + Tau_xz*wface + Qx)*nx) + &
                          ((Tau_yx*uface + Tau_yy*vface + Tau_yz*wface + Qy)*ny) + &
                          ((Tau_zx*uface + Tau_zy*vface + Tau_zz*wface + Qz)*nz) ) )
        end do
       end do
      end do
    end subroutine compute_viscous_fluxes_laminar
Call graph
compute_viscous_fluxes calls compute_viscous_fluxes_laminar
get_total_conservative_residue calls compute_viscous_fluxes
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step