compute_ghost_cell_centroid – FEST-3D
compute_ghost_cell_centroid Subroutine
13 statements
Source File
private subroutine compute_ghost_cell_centroid()
compute cell center of all cell including ghost cells
Arguments
None
Called by
Contents
Source Code
compute_ghost_cell_centroid
Source Code
        subroutine compute_ghost_cell_centroid()
          !< compute cell center of all cell including ghost cells
          implicit none
          integer :: i,j,k
          do k = -2, kmx+2
            do j = -2, jmx+2
              do i = -2, imx+2
                CellCenter(i,j,k,1) = 0.125 * ( grid_x(i  ,j  ,k  ) &
                                              + grid_x(i+1,j  ,k  ) &
                                              + grid_x(i+1,j+1,k  ) &
                                              + grid_x(i+1,j+1,k+1) &
                                              + grid_x(i+1,j  ,k+1) &
                                              + grid_x(i  ,j+1,k  ) &
                                              + grid_x(i  ,j+1,k+1) &
                                              + grid_x(i  ,j  ,k+1) &
                                              )
                CellCenter(i,j,k,2) = 0.125 * ( grid_y(i  ,j  ,k  ) &
                                              + grid_y(i+1,j  ,k  ) &
                                              + grid_y(i+1,j+1,k  ) &
                                              + grid_y(i+1,j+1,k+1) &
                                              + grid_y(i+1,j  ,k+1) &
                                              + grid_y(i  ,j+1,k  ) &
                                              + grid_y(i  ,j+1,k+1) &
                                              + grid_y(i  ,j  ,k+1) &
                                              )
                CellCenter(i,j,k,3) = 0.125 * ( grid_z(i  ,j  ,k  ) &
                                              + grid_z(i+1,j  ,k  ) &
                                              + grid_z(i+1,j+1,k  ) &
                                              + grid_z(i+1,j+1,k+1) &
                                              + grid_z(i+1,j  ,k+1) &
                                              + grid_z(i  ,j+1,k  ) &
                                              + grid_z(i  ,j+1,k+1) &
                                              + grid_z(i  ,j  ,k+1) &
                                              )
              end do
            end do
          end do
        end subroutine compute_ghost_cell_centroid
Call graph
setup_geometry calls compute_ghost_cell_centroid
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run