compute_residue – FEST-3D
compute_residue Subroutine
19 statements
Source File
public subroutine compute_residue(residue, F, G, H, dims)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(:, :, :, :) :: residue
Store residue at each cell-center
real(kind=wp), intent(in), dimension(:, :, :, :) :: F
Store fluxes throught the I faces
real(kind=wp), intent(in), dimension(:, :, :, :) :: G
Store fluxes throught the J faces
real(kind=wp), intent(in), dimension(:, :, :, :) :: H
Store fluxes throught the K faces
type(extent), intent(in) :: dims
extent of the 3D domain
Calls
Called by
Contents
Source Code
compute_residue
Source Code
        subroutine compute_residue(residue,F,G,H,dims)
            implicit none
            type(extent), intent(in) :: dims
            !< extent of the 3D domain
            real(wp), dimension(:, :, :, :), intent(out)  :: residue
            !< Store residue at each cell-center
            real(wp), dimension(:, :, :, :), intent(in) :: F
            !< Store fluxes throught the I faces
            real(wp), dimension(:, :, :, :), intent(in) :: G
            !< Store fluxes throught the J faces
            real(wp), dimension(:, :, :, :), intent(in) :: H
            !< Store fluxes throught the K faces
            integer :: i, j, k, l
            DebugCall('compute_residue')
            do l = 1, dims%n_var
             do k = 1, dims%kmx - 1
              do j = 1, dims%jmx - 1
               do i = 1, dims%imx - 1
               residue(i, j, k, l) = (F(i+1, j, k, l) - F(i, j, k, l)) &
                                   + (G(i, j+1, k, l) - G(i, j, k, l)) &
                                   + (H(i, j, k+1, l) - H(i, j, k, l))
               end do
              end do
             end do
            end do
        end subroutine compute_residue
Call graph
compute_residue calls debugcall
get_total_conservative_residue calls compute_residue
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step