compute_face_interpolant – FEST-3D
compute_face_interpolant Subroutine
22 statements
Source File
public subroutine compute_face_interpolant(qp, cells, scheme, flow, dims)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-2:dims%imx+2, -2:dims%jmx+2, -2:dims%kmx+2, 1:dims%n_var) :: qp
Store primitive variable at cell center
type(celltype), intent(in), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2) :: cells
Cell center quantities: volume, cellCenter
type(schemetype), intent(in) :: scheme
finite-volume Schemes
type(flowtype), intent(in) :: flow
Information about fluid flow: freestream-speed, ref-viscosity,etc.
type(extent), intent(in) :: dims
Extent of the domain:imx,jmx,kmx
Calls
Called by
Contents
Source Code
compute_face_interpolant
Source Code
        subroutine compute_face_interpolant(qp, cells, scheme, flow, dims)
            implicit none
            type(extent), intent(in) :: dims
            !< Extent of the domain:imx,jmx,kmx
            real(wp), dimension(-2:dims%imx+2, -2:dims%jmx+2, -2:dims%kmx+2, 1:dims%n_var), intent(in):: qp
            !< Store primitive variable at cell center
            type(celltype), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2), intent(in) :: cells
            !< Cell center quantities: volume, cellCenter
            type(schemetype), intent(in) :: scheme
            !< finite-volume Schemes
            type(flowtype), intent(in) :: flow
            !< Information about fluid flow: freestream-speed, ref-viscosity,etc.
            select case (scheme%interpolant)
                case ("none")
                    call extrapolate_cell_averages_to_faces(qp, dims)
                case ("ppm")
                    call compute_ppm_states(qp,  x_qp_left, x_qp_right, y_qp_left, y_qp_right, z_qp_left, z_qp_right, pdif, scheme, flow, dims)
                case ("muscl")
                    call compute_muscl_states(qp, x_qp_left, x_qp_right, y_qp_left, y_qp_right, z_qp_left, z_qp_right, pdif, scheme, flow, dims)
                case ("weno")
                    call compute_weno_states(qp, x_qp_left, x_qp_right, y_qp_left, y_qp_right, z_qp_left, z_qp_right, dims)
                case ("weno_NM")
                    call compute_weno_NM_states(qp, x_qp_left, x_qp_right, y_qp_left, y_qp_right, z_qp_left, z_qp_right, cells, dims)
                case default
                    Fatal_error
            end select
        end subroutine compute_face_interpolant
Call graph
compute_face_interpolant calls compute_ppm_states, extrapolate_cell_averages_to_faces, compute_muscl_states, compute_weno_nm_states, compute_weno_states
compute_ppm_states calls pressure_based_switching, remove_extrema, compute_face_estimates
extrapolate_cell_averages_to_faces calls debugcall
compute_muscl_states calls compute_face_state, pressure_based_switching
compute_weno_nm_states calls compute_face_states
compute_weno_states calls compute_face_states
pressure_based_switching calls debugcall
remove_extrema calls debugcall
compute_face_estimates calls debugcall
compute_face_state calls debugcall
get_total_conservative_residue calls compute_face_interpolant
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step