compute_face_area_vectors – FEST-3D
compute_face_area_vectors Subroutine
50 statements
Source File
private subroutine compute_face_area_vectors()
Compute face area vectors
The face area vectors denote the face area both in magnitude and direction. They are placed in the face normal variables for further calculation.
The face normal is given by d1 x d2, where d1 and d2 are the diagonals of a face
Arguments
None
Called by
Contents
Source Code
compute_face_area_vectors
Source Code
        subroutine compute_face_area_vectors()
            !< Compute face area vectors
            !<
            !< The face area vectors denote the face area both in
            !< magnitude and direction. They are placed in the face
            !< normal variables for further calculation.
            !<
            !< The face normal is given by d1 x d2, where d1 and d2 are
            !< the diagonals of a face
            !-----------------------------------------------------------
            implicit none
            real :: d1x, d2x, d1y, d2y, d1z, d2z
            integer :: i, j, k
            do k = -2, kmx+2
             do j = -2, jmx+2
              do i = -2, imx+3
                d1x = grid_x(i, j+1, k+1) - grid_x(i, j, k)
                d1y = grid_y(i, j+1, k+1) - grid_y(i, j, k)
                d1z = grid_z(i, j+1, k+1) - grid_z(i, j, k)
                d2x = grid_x(i, j, k+1) - grid_x(i, j+1, k)
                d2y = grid_y(i, j, k+1) - grid_y(i, j+1, k)
                d2z = grid_z(i, j, k+1) - grid_z(i, j+1, k)
                xnx(i, j, k) = 0.5 * (d1y*d2z - d1z*d2y)
                xny(i, j, k) = 0.5 * (d1z*d2x - d1x*d2z)
                xnz(i, j, k) = 0.5 * (d1x*d2y - d1y*d2x)
               end do
              end do
             end do
            do k = -2, kmx+2
             do j = -2, jmx+3
              do i = -2, imx+2
               d1x = grid_x(i+1, j, k+1) - grid_x(i, j, k)
               d1y = grid_y(i+1, j, k+1) - grid_y(i, j, k)
               d1z = grid_z(i+1, j, k+1) - grid_z(i, j, k)
               d2x = grid_x(i+1, j, k) - grid_x(i, j, k+1)
               d2y = grid_y(i+1, j, k) - grid_y(i, j, k+1)
               d2z = grid_z(i+1, j, k) - grid_z(i, j, k+1)
               ynx(i, j, k) = 0.5 * (d1y*d2z - d1z*d2y)
               yny(i, j, k) = 0.5 * (d1z*d2x - d1x*d2z)
               ynz(i, j, k) = 0.5 * (d1x*d2y - d1y*d2x)
              end do
             end do
            end do
            do k = -2, kmx+3
             do j = -2, jmx+2
              do i = -2, imx+2
               d1x = grid_x(i+1, j+1, k) - grid_x(i, j, k)
               d1y = grid_y(i+1, j+1, k) - grid_y(i, j, k)
               d1z = grid_z(i+1, j+1, k) - grid_z(i, j, k)
               d2x = grid_x(i, j+1, k) - grid_x(i+1, j, k)
               d2y = grid_y(i, j+1, k) - grid_y(i+1, j, k)
               d2z = grid_z(i, j+1, k) - grid_z(i+1, j, k)
               znx(i, j, k) = 0.5 * (d1y*d2z - d1z*d2y)
               zny(i, j, k) = 0.5 * (d1z*d2x - d1x*d2z)
               znz(i, j, k) = 0.5 * (d1x*d2y - d1y*d2x)
              end do
             end do
            end do
        end subroutine compute_face_area_vectors
Call graph
compute_face_areas_and_normals calls compute_face_area_vectors
compute_geometric_parameters calls compute_face_areas_and_normals
setup_geometry calls compute_geometric_parameters
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run