compute_geometric_parameters – FEST-3D
compute_geometric_parameters Subroutine
6 statements
Source File
private subroutine compute_geometric_parameters()
Compute the geometric parameters based on the grid points
The geometric parameters include the face normals and areas and the cell volumes.
Arguments
None
Calls
Called by
Contents
Source Code
compute_geometric_parameters
Source Code
        subroutine compute_geometric_parameters()
            !< Compute the geometric parameters based on the grid points
            !<
            !< The geometric parameters include the face normals and
            !< areas and the cell volumes.
            !-----------------------------------------------------------
            implicit none
            call dmsg(1, 'geometry', 'compute_geometric_parameters')
            call compute_face_areas_and_normals()
            call compute_volumes()
        end subroutine compute_geometric_parameters
Call graph
compute_geometric_parameters calls compute_face_areas_and_normals, dmsg, compute_volumes
compute_face_areas_and_normals calls compute_face_area_vectors, compute_face_areas, normalize_face_normals
compute_volumes calls vol_hexahedron
vol_hexahedron calls vol_tetrahedron
setup_geometry calls compute_geometric_parameters
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run