compute_gradient – FEST-3D
compute_gradient Subroutine
43 statements
Source File
private subroutine compute_gradient(grad, var, dir)
Generalized subroutine to calculate gradients
Arguments
Type Intent Optional Attributes Name
real, intent(out), dimension(-2:imx+2,-2:jmx+2,-2:kmx+2) :: grad
real, intent(in), dimension(-2:imx+2,-2:jmx+2,-2:kmx+2) :: var
character(len=*), intent(in) :: dir
Called by
Contents
Source Code
compute_gradient
Source Code
    subroutine compute_gradient(grad, var, dir)
      !< Generalized subroutine to calculate gradients
      implicit none
      real, dimension(-2:imx+2,-2:jmx+2,-2:kmx+2), intent(out) :: grad
      real, dimension(-2:imx+2,-2:jmx+2,-2:kmx+2), intent(in) :: var
      character(len=*)                           , intent(in) :: dir
      real, dimension(:,:,:), pointer  :: nx
      real, dimension(:,:,:), pointer  :: ny
      real, dimension(:,:,:), pointer  :: nz
      integer :: i
      integer :: j
      integer :: k
      ! initialize
      grad = 0.0
      select case(dir)
        case('x')
          nx(-2:imx+3,-2:jmx+2,-2:kmx+2) => xn(:,:,:,1)
          ny(-2:imx+2,-2:jmx+3,-2:kmx+2) => yn(:,:,:,1)
          nz(-2:imx+2,-2:jmx+2,-2:kmx+3) => zn(:,:,:,1)
        case('y')
          nx(-2:imx+3,-2:jmx+2,-2:kmx+2) => xn(:,:,:,2)
          ny(-2:imx+2,-2:jmx+3,-2:kmx+2) => yn(:,:,:,2)
          nz(-2:imx+2,-2:jmx+2,-2:kmx+3) => zn(:,:,:,2)
        case('z')
          nx(-2:imx+3,-2:jmx+2,-2:kmx+2) => xn(:,:,:,3)
          ny(-2:imx+2,-2:jmx+3,-2:kmx+2) => yn(:,:,:,3)
          nz(-2:imx+2,-2:jmx+2,-2:kmx+3) => zn(:,:,:,3)
        case DEFAULT
          nx(-2:imx+3,-2:jmx+2,-2:kmx+2) => xn(:,:,:,1)
          ny(-2:imx+2,-2:jmx+3,-2:kmx+2) => yn(:,:,:,1)
          nz(-2:imx+2,-2:jmx+2,-2:kmx+3) => zn(:,:,:,1)
          print*, "ERROR: gradient direction error"
      end select
      grad = 0.0
      do k=0,kmx
        do j=0,jmx
          do i=0,imx
            grad(i,j,k) =(-(var(i-1,j  ,k  )+var(i,j,k))*nx(i,j,k)*xA(i,j,k) &
                          -(var(i  ,j-1,k  )+var(i,j,k))*ny(i,j,k)*yA(i,j,k) &
                          -(var(i  ,j  ,k-1)+var(i,j,k))*nz(i,j,k)*zA(i,j,k) &
                          +(var(i+1,j  ,k  )+var(i,j,k))*nx(i+1,j  ,k  )*xA(i+1,j  ,k  ) &
                          +(var(i  ,j+1,k  )+var(i,j,k))*ny(i  ,j+1,k  )*yA(i  ,j+1,k  ) &
                          +(var(i  ,j  ,k+1)+var(i,j,k))*nz(i  ,j  ,k+1)*zA(i  ,j  ,k+1) &
                         )/(2*volume(i,j,k))
          end do
        end do
      end do
      if(any(isnan(grad)))then
        Fatal_error
      end if
    end subroutine compute_gradient
Call graph
find_ccnormal calls compute_gradient
find_dccvn calls compute_gradient
setupcc calls find_ccnormal
add_sst_source_lctm2015 calls find_dccvn
setup_solver calls setupcc
add_source_term_residue calls add_sst_source_lctm2015
get_total_conservative_residue calls add_source_term_residue
start_run calls setup_solver
main calls start_run, iterate_one_more_time_step
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution