compute_global_time_step – FEST-3D
compute_global_time_step Subroutine
10 statements
Source File
private subroutine compute_global_time_step()
Compute a common time step to be used at all cell centers
Global time stepping is generally used to get time accurate solutions; transients can be studied by employing this strategy.
Arguments
None
Calls
Called by
Contents
Source Code
compute_global_time_step
Source Code
        subroutine compute_global_time_step()
            !< Compute a common time step to be used at all cell centers
            !<
            !< Global time stepping is generally used to get time
            !< accurate solutions; transients can be studied by
            !< employing this strategy.
            !<-----------------------------------------------------------
            implicit none
            call dmsg(1, 'solver', 'compute_global_time_step')
            if (global_time_step > 0) then
                delta_t = global_time_step
            else
                call compute_local_time_step()
                ! The global time step is the minimum of all the local time
                ! steps.
                delta_t = minval(delta_t)
            end if
        end subroutine compute_global_time_step
Call graph
compute_global_time_step calls compute_local_time_step, dmsg
compute_local_time_step calls dmsg, add_viscous_time, add_turbulent_time, x_qp_right, x_qp_left, y_qp_left, z_qp_left, y_qp_right, z_qp_right
add_viscous_time calls dmsg
add_turbulent_time calls dmsg
compute_time_step calls compute_global_time_step
get_next_solution calls compute_time_step
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step