deallocate_memory – FEST-3D
deallocate_memory Subroutine
12 statements
Source File
private subroutine deallocate_memory()
Deallocate the memoery used by the geometry variables
Arguments
None
Calls
Called by
Contents
Source Code
deallocate_memory
Source Code
        subroutine deallocate_memory()
          !< Deallocate the memoery used by the geometry variables
            implicit none
            call dmsg(1, 'geometry', 'deallocate_memory')
            call dealloc(xn)
            call dealloc(yn)
            call dealloc(zn)
            call dealloc(xA)
            call dealloc(yA)
            call dealloc(zA)
            call dealloc(volume)
            call dealloc(CellCenter)
!            call dealloc(left_ghost_centroid)
!            call dealloc(right_ghost_centroid)
!            call dealloc(front_ghost_centroid)
!            call dealloc(back_ghost_centroid)
!            call dealloc(top_ghost_centroid)
!            call dealloc(bottom_ghost_centroid)
        end subroutine deallocate_memory
Call graph
deallocate_memory calls dealloc, dmsg
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_geometry calls deallocate_memory
destroy_all calls destroy_geometry
destroy_solver calls destroy_geometry
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run