deallocate_memory – FEST-3D
deallocate_memory Subroutine
5 statements
Source File
private subroutine deallocate_memory()
Deallocate memory from the Wallc array
Arguments
None
Calls
Called by
Contents
Source Code
deallocate_memory
Source Code
    subroutine deallocate_memory()
      !< Deallocate memory from the Wallc array
      implicit none
      call dmsg(1, 'wall_find', 'dealloate_memory')
      call dealloc(wallc)
    end subroutine deallocate_memory
Call graph
deallocate_memory calls dealloc, dmsg
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_surface calls deallocate_memory
write_surfnode calls destroy_surface
setup_solver calls write_surfnode
setup_all calls write_surfnode
start_run calls setup_solver
main calls start_run