deallocate_memory – FEST-3D
deallocate_memory Subroutine
9 statements
Source File
private subroutine deallocate_memory()
Deallocate memory required for MPI Communication
Arguments
None
Calls
Called by
Contents
Source Code
deallocate_memory
Source Code
    subroutine deallocate_memory()
      !< Deallocate memory required for MPI Communication
      implicit none
      call dealloc(Res_abs)
      call dealloc(Res_rel)
      call dealloc(Res_scale)
      call dealloc(Res_save)
      call dealloc(buffer)
      if(allocated(Res_list)) deallocate(Res_list)
    end subroutine deallocate_memory
Call graph
deallocate_memory calls dealloc
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_resnorm calls deallocate_memory
destroy_solver calls destroy_resnorm
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run