dealloc_rank3_integer – FEST-3D
dealloc_rank3_integer Subroutine
11 statements
Source File
private subroutine dealloc_rank3_integer(var)
Deallcoate 3-Dimensional array of type: integer
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:, :, :), allocatable :: var
Variable to which memeory is deallocated
Called by
Contents
None
Call graph
dealloc calls dealloc_rank3_integer
destroy_lusgs calls dealloc
destroy_scheme calls dealloc
destroy_update calls dealloc, destroy_lusgs, destroy_plusgs
destroy_time calls dealloc
destroy_bc calls dealloc
deallocate_memory calls dealloc
destroy_memory calls dealloc
destroy_grid calls dealloc
find_wall_dist calls dealloc
destroy_wall_dist calls dealloc
destroycc calls dealloc
destroy_interface calls dealloc
destroy_viscosity calls dealloc
destroy_plusgs calls dealloc
setup_solver calls find_wall_dist, write_surfnode
destroy_gradients calls destroy_memory
destroy_resnorm calls deallocate_memory
destroy_state calls deallocate_memory
destroy_solver calls destroy_update, destroy_time, destroy_bc, destroy_grid, destroy_wall_dist, destroycc, destroy_interface, destroy_viscosity, destroy_gradients, destroy_resnorm, destroy_state, destroy_geometry
setup_all calls find_wall_dist, write_surfnode
destroy_all calls destroy_time, destroy_grid, destroy_wall_dist, destroy_gradients, destroy_state, destroy_geometry
destroy_geometry calls deallocate_memory
destroy_surface calls deallocate_memory
finish_run calls destroy_solver
abort_run calls destroy_solver
write_surfnode calls destroy_surface
start_run calls setup_solver
main calls finish_run, start_run