destroy_resnorm – FEST-3D
destroy_resnorm Subroutine
5 statements
Source File
public subroutine destroy_resnorm()
deallocate memory and close residual file
Arguments
None
Calls
Called by
Contents
Source Code
destroy_resnorm
Source Code
    subroutine destroy_resnorm()
      !< deallocate memory and close residual file
      implicit none
      call deallocate_memory()
      call close_file(RESNORM_FILE_UNIT)
    end subroutine destroy_resnorm
Call graph
destroy_resnorm calls close_file, deallocate_memory
deallocate_memory calls dealloc
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_solver calls destroy_resnorm
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run