destroy_interface – FEST-3D
destroy_interface Subroutine
15 statements
Source File
public subroutine destroy_interface()
Deallocate all the memory being used for data communication between processors
Arguments
None
Calls
Called by
Contents
Source Code
destroy_interface
Source Code
    subroutine destroy_interface()
      !< Deallocate all the memory being used  for data communication between processors
      implicit none
      call dealloc(imin_send_buf)
      call dealloc(jmin_send_buf)
      call dealloc(kmin_send_buf)
      call dealloc(imin_recv_buf)
      call dealloc(jmin_recv_buf)
      call dealloc(kmin_recv_buf)
      call dealloc(imax_send_buf)
      call dealloc(jmax_send_buf)
      call dealloc(kmax_send_buf)
      call dealloc(imax_recv_buf)
      call dealloc(jmax_recv_buf)
      call dealloc(kmax_recv_buf)
    end subroutine destroy_interface
Call graph
destroy_interface calls dealloc
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_solver calls destroy_interface
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run