destroy_geometry – FEST-3D
destroy_geometry Subroutine
14 statements
Source File
public subroutine destroy_geometry()
Nullify all the face normal pionter
Arguments
None
Calls
Called by
Contents
Source Code
destroy_geometry
Source Code
        subroutine destroy_geometry()
          !< Nullify all the face normal pionter
            implicit none
            call dmsg(1, 'geometry', 'destroy_geometry')
            nullify(xnx)
            nullify(xny)
            nullify(xnz)
            nullify(ynx)
            nullify(yny)
            nullify(ynz)
            nullify(znx)
            nullify(zny)
            nullify(znz)
            call deallocate_memory()
        end subroutine destroy_geometry
Call graph
destroy_geometry calls deallocate_memory, dmsg
deallocate_memory calls dmsg, dealloc
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_all calls destroy_geometry
destroy_solver calls destroy_geometry
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run