destroy_gradients – FEST-3D
destroy_gradients Subroutine
28 statements
Source File
public subroutine destroy_gradients()
Deallocate memoery and nullify pointers to the gradient variables.
Arguments
None
Calls
Called by
Contents
Source Code
destroy_gradients
Source Code
    subroutine destroy_gradients
      !< Deallocate memoery and nullify pointers
      !< to the gradient variables.
      implicit none
      DebugCall("destroy_gradients")
      if(mu_ref/=0)then
        call destroy_memory()
        ! unlink laminar grad pointer
        call destroy_laminar_grad()
        !unlink turublent grad pointer
        select case (trim(turbulence))
          case('none')
            !do nothing
            continue
          case('sa', 'saBC')
            call destroy_sa_grad()
          case('sst', 'sst2003')
            call destroy_sst_grad()
          case('kkl')
            call destroy_kkl_grad()
          case DEFAULT
           ! call turbulence_read_error()
           Fatal_error
        end select
        !Transition modeling
        select case(trim(transition))
          case('lctm2015')
            call destroy_lctm2015_grad()
          case('none','bc')
            !do nothing
            continue
          case DEFAULT
            Fatal_error
        end Select
      end if
    end subroutine destroy_gradients
Call graph
destroy_gradients calls destroy_sst_grad, destroy_memory, destroy_sa_grad, destroy_kkl_grad, debugcall, destroy_laminar_grad, destroy_lctm2015_grad
destroy_sst_grad calls debugcall
destroy_memory calls debugcall, dealloc
destroy_sa_grad calls debugcall
destroy_kkl_grad calls debugcall
destroy_laminar_grad calls debugcall
destroy_lctm2015_grad calls debugcall
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_all calls destroy_gradients
destroy_solver calls destroy_gradients
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run