destroy_bc – FEST-3D
destroy_bc Subroutine
6 statements
Source File
public subroutine destroy_bc()
Deallocate memory from boundary condition variables
Arguments
None
Calls
Called by
Contents
Source Code
destroy_bc
Source Code
    subroutine destroy_bc()
      !< Deallocate memory from boundary condition variables
      implicit none
      call dealloc(make_F_flux_zero)
      call dealloc(make_G_flux_zero)
      call dealloc(make_H_flux_zero)
    end subroutine destroy_bc
Call graph
destroy_bc calls dealloc
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_solver calls destroy_bc
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run