destroyCC – FEST-3D
destroyCC Subroutine
11 statements
Source File
public subroutine destroyCC()
Deallocate memory from the cell-center variables.
Arguments
None
Calls
Called by
Contents
Source Code
destroyCC
Source Code
    subroutine destroyCC()
      !< Deallocate memory from the cell-center variables.
      implicit none
      DebugCall("Destroy CC")
      call dealloc(CCnormalX)
      call dealloc(CCnormalY)
      call dealloc(CCnormalZ)
      call dealloc(CCVn)
      call dealloc(DCCVnX)
      call dealloc(DCCVnY)
      call dealloc(DCCVnZ)
    end subroutine destroyCC
Call graph
destroycc calls dealloc, debugcall
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_solver calls destroycc
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run