destroy_surface – FEST-3D
destroy_surface Subroutine
7 statements
Source File
private subroutine destroy_surface()
Deallocate memory, unlink pointers, and close MPI_shared file
Arguments
None
Calls
Called by
Contents
Source Code
destroy_surface
Source Code
    subroutine destroy_surface()
      !< Deallocate memory, unlink pointers, and close MPI_shared file
      implicit none
      call dmsg(1, 'wall_find', 'destroy_surface')
      call deallocate_memory()
      call unlink_aliases()
      call MPI_FILE_CLOSE(thisfile, ierr)
    end subroutine destroy_surface
Call graph
destroy_surface calls deallocate_memory, mpi_file_close, dmsg, unlink_aliases
deallocate_memory calls dmsg, dealloc
unlink_aliases calls dmsg
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
write_surfnode calls destroy_surface
setup_solver calls write_surfnode
setup_all calls write_surfnode
start_run calls setup_solver
main calls start_run