destroy_grid – FEST-3D
destroy_grid Subroutine
7 statements
Source File
public subroutine destroy_grid()
Deallocate the memory allocated for the grid.
Arguments
None
Calls
Called by
Contents
Source Code
destroy_grid
Source Code
        subroutine destroy_grid()
            !< Deallocate the memory allocated for the grid.
            !-----------------------------------------------------------
            implicit none
            call dmsg(1, 'grid', 'destroy_memory')
            call dealloc(grid_x)
            call dealloc(grid_y)
            call dealloc(grid_z)
!           call dealloc(sphere_indices)
        end subroutine destroy_grid
Call graph
destroy_grid calls dealloc, dmsg
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_all calls destroy_grid
destroy_solver calls destroy_grid
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run