destroy_all – FEST-3D
destroy_all Subroutine
19 statements
Source File
public subroutine destroy_all()
free memory and free pointers
Arguments
None
Calls
Contents
Source Code
destroy_all
Source Code
      subroutine destroy_all()
          !< free memory and free pointers
          implicit none
          call dmsg(1, 'create_erase', 'destroy_all')
          call destroy_time()
          call destroy_transport()
          call destroy_gradients()
          call destroy_wall_dist()
          call destroy_scheme()
          call deallocate_misc()
          call unlink_aliases_solver()
          call destroy_state()
          call destroy_geometry()
          call destroy_grid()
          call destroy_resnorm()
          call destroy_sst_F1()
          if(allocated(r_list)) deallocate(r_list)
          if(allocated(w_list)) deallocate(w_list)
          call dmsg(5, 'create_erase', 'destroy_all', 'Memory_freed')
      end subroutine destroy_all
Call graph
destroy_all calls destroy_resnorm, destroy_time, destroy_gradients, destroy_transport, destroy_grid, destroy_sst_f1, destroy_scheme, destroy_state, destroy_geometry, deallocate_misc, dmsg, destroy_wall_dist, unlink_aliases_solver
destroy_time calls dmsg, alloc, mpi_gather, dealloc, write_time
destroy_gradients calls destroy_sst_grad, destroy_memory, destroy_sa_grad, destroy_kkl_grad, debugcall, destroy_laminar_grad, destroy_lctm2015_grad
destroy_grid calls dmsg, dealloc
destroy_state calls deallocate_memory, debugcall, unlink_aliases
destroy_geometry calls dmsg, deallocate_memory
destroy_wall_dist calls dmsg, dealloc
deallocate_memory calls dmsg, dealloc, debugcall
destroy_sst_grad calls debugcall
destroy_memory calls dealloc, debugcall
destroy_sa_grad calls debugcall
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
destroy_kkl_grad calls debugcall
dealloc calls dealloc_rank6_real, dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank5_real, dealloc_rank3_real
unlink_aliases calls debugcall
destroy_laminar_grad calls debugcall
destroy_lctm2015_grad calls debugcall