destroy_state – FEST-3D
destroy_state Subroutine
6 statements
Source File
public subroutine destroy_state()
Destroy the state module. This subroutine destroys the state module which includes unlinking the aliases for the state components and deallocating the memory held by the state variables.
Arguments
None
Calls
Called by
Contents
Source Code
destroy_state
Source Code
        subroutine destroy_state()
            !< Destroy the state module.
            !< This subroutine destroys the state module which includes
            !< unlinking the aliases for the state components and
            !< deallocating the memory held by the state variables.
            !-----------------------------------------------------------
            implicit none
            DebugCall("destroy_state")
            call unlink_aliases()
            call deallocate_memory()
        end subroutine destroy_state
Call graph
destroy_state calls deallocate_memory, unlink_aliases, debugcall
deallocate_memory calls debugcall, dealloc
unlink_aliases calls debugcall
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_all calls destroy_state
destroy_solver calls destroy_state
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run