destroy_kkl_grad – FEST-3D
destroy_kkl_grad Subroutine
10 statements
Source File
public subroutine destroy_kkl_grad()
nullify all the gradient pointer setup for k-kL model
Arguments
None
Calls
Called by
Contents
Source Code
destroy_kkl_grad
Source Code
    subroutine destroy_kkl_grad()
      !< nullify all the gradient pointer setup for k-kL model
      implicit none
      DebugCall('destroy_kkl_grad')
      nullify(gradtk_x)
      nullify(gradtkl_x)
      nullify(gradtk_y)
      nullify(gradtkl_y)
      nullify(gradtk_z)
      nullify(gradtkl_z)
    end subroutine destroy_kkl_grad
Call graph
destroy_kkl_grad calls debugcall
destroy_gradients calls destroy_kkl_grad
destroy_all calls destroy_gradients
destroy_solver calls destroy_gradients
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run