destroy_scheme – FEST-3D
destroy_scheme Subroutine
10 statements
Source File
public subroutine destroy_scheme()
Deallocate all the array used
Arguments
None
Calls
Contents
Source Code
destroy_scheme
Source Code
        subroutine destroy_scheme()
          !< Deallocate all the array used
            implicit none
            call dmsg(1, 'weno_NM', 'destroy_weno_NM')
            call dealloc(x_qp_left)
            call dealloc(x_qp_right)
            call dealloc(y_qp_left)
            call dealloc(y_qp_right)
            call dealloc(z_qp_left)
            call dealloc(z_qp_right)
        end subroutine destroy_scheme
Call graph
destroy_scheme calls dealloc, dmsg
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real