destroy_memory – FEST-3D
destroy_memory Subroutine
7 statements
Source File
private subroutine destroy_memory()
deallocate memeory from the gradient variables
Arguments
None
Calls
Called by
Contents
Source Code
destroy_memory
Source Code
    subroutine destroy_memory()
      !< deallocate memeory from the gradient variables
      implicit none
      DebugCall("deallocate_memory")
      call dealloc(gradqp_x)
      call dealloc(gradqp_y)
      call dealloc(gradqp_z)
    end subroutine destroy_memory
Call graph
destroy_memory calls dealloc, debugcall
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_gradients calls destroy_memory
destroy_all calls destroy_gradients
destroy_solver calls destroy_gradients
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run