destroy_plusgs – FEST-3D
destroy_plusgs Subroutine
18 statements
Source File
public subroutine destroy_plusgs()
unallocate the memory required by LU-SGS module
Arguments
None
Calls
Called by
Contents
Source Code
destroy_plusgs
Source Code
    subroutine destroy_plusgs()
      !< unallocate the memory required by LU-SGS module
      implicit none
      call dealloc(imin_send_buf)
      call dealloc(jmin_send_buf)
      call dealloc(kmin_send_buf)
      call dealloc(imin_recv_buf)
      call dealloc(jmin_recv_buf)
      call dealloc(kmin_recv_buf)
      call dealloc(imax_send_buf)
      call dealloc(jmax_send_buf)
      call dealloc(kmax_send_buf)
      call dealloc(imax_recv_buf)
      call dealloc(jmax_recv_buf)
      call dealloc(kmax_recv_buf)
      call dealloc(delQ)
      call dealloc(delQstar)
      call dealloc(dummy)
    end subroutine destroy_plusgs
Call graph
destroy_plusgs calls dealloc
dealloc calls dealloc_rank2_real, dealloc_rank4_real, dealloc_rank1_integer, dealloc_rank2_integer, dealloc_rank1_real, dealloc_rank3_integer, dealloc_rank3_real, dealloc_rank5_real, dealloc_rank6_real
destroy_update calls destroy_plusgs
destroy_solver calls destroy_update
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run