destroy_solver – FEST-3D
destroy_solver Subroutine
25 statements
Source File
public subroutine destroy_solver()
Call to different modules to deallocate memory
Arguments
None
Calls
Called by
Contents
Source Code
destroy_solver
Source Code
        subroutine destroy_solver()
          !< Call to different modules to deallocate memory
          !--------------------------------------------------
            implicit none
            call dmsg(1, 'solver', 'destroy_solver')
            if(process_id==0)then
              close(STOP_FILE_UNIT)
            end if
            call destroy_update()
            call destroy_viscosity()
            call destroy_gradients()
            call destroyCC()
            if(turbulence /= 'none') then
              call destroy_wall_dist()
            end if
            call destroy_scheme()
            call destroy_source()
            call destroy_state()
            call destroy_geometry()
            call destroy_grid()
            call destroy_resnorm()
            call destroy_interface()
            call destroy_time()
            call destroy_bc()
            if(allocated(r_list)) deallocate(r_list)
            if(allocated(w_list)) deallocate(w_list)
        end subroutine destroy_solver
Call graph
destroy_solver calls destroycc, destroy_time, destroy_gradients, destroy_grid, destroy_resnorm, destroy_scheme, destroy_state, destroy_interface, destroy_geometry, destroy_viscosity, dmsg, destroy_update, destroy_wall_dist, destroy_bc, destroy_source
destroycc calls dealloc, debugcall
destroy_time calls dmsg, alloc, mpi_gather, dealloc, write_time
destroy_gradients calls destroy_sst_grad, destroy_memory, destroy_sa_grad, destroy_kkl_grad, debugcall, destroy_laminar_grad, destroy_lctm2015_grad
destroy_grid calls dmsg, dealloc
destroy_resnorm calls close_file, deallocate_memory
destroy_state calls deallocate_memory, debugcall, unlink_aliases
destroy_interface calls dealloc
destroy_geometry calls dmsg, deallocate_memory
destroy_viscosity calls dealloc
destroy_update calls destroy_lusgs, destroy_plusgs, dealloc
destroy_wall_dist calls dmsg, dealloc
destroy_bc calls dealloc
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run