dump_data – FEST-3D
dump_data Subroutine
14 statements
Source File
private subroutine dump_data(files, qp, nodes, control, scheme, dims)
Call to write save files in the directory
Arguments
Type Intent Optional Attributes Name
type(filetype), intent(inout) :: files
real(kind=wp), intent(in), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2, 1:dims%n_var) :: qp
type(nodetype), intent(in), dimension(-2:dims%imx+3,-2:dims%jmx+3,-2:dims%kmx+3) :: nodes
type(controltype), intent(in) :: control
type(schemetype), intent(in) :: scheme
type(extent), intent(in) :: dims
Calls
Called by
Contents
Source Code
dump_data
Source Code
    subroutine dump_data(files, qp, nodes, control, scheme, dims)
      !< Call to write save files in the directory
      implicit none
      type(filetype), intent(inout) :: files
      type(extent), intent(in) :: dims
      type(controltype), intent(in) :: control
      type(schemetype), intent(in) :: scheme
      type(nodetype), dimension(-2:dims%imx+3,-2:dims%jmx+3,-2:dims%kmx+3), intent(in) :: nodes
      real(wp), dimension(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2, 1:dims%n_var), intent(in) :: qp
      DebugCall('dump_solution: dump_data')
      write(files%restartfile, '(A,I2.2)') trim(dump_dirname)//'/restart/process_',process_id
      write(files%outfile, '(A,I2.2)') trim(dump_dirname)//'/process_',process_id
      call write_restart_log(files, scheme, control)
      call write_file(files, qp, nodes, control, scheme, dims)
    end subroutine dump_data
Call graph
dump_data calls debugcall, write_restart_log, write_file
write_restart_log calls write_initial_resnorm
write_file calls close_file, write_file_tec_nodal, open_file, setup_file, write_file_vtk, write_file_tec
close_file calls debugcall
open_file calls debugcall
setup_file calls debugcall
checkpoint calls dump_data
setup_solver calls checkpoint
iterate_one_more_time_step calls checkpoint
main calls iterate_one_more_time_step, start_run
start_run calls setup_solver