fill_fixed_values – FEST-3D
fill_fixed_values Subroutine
29 statements
Source File
private subroutine fill_fixed_values()
fill the Fixed_var array with with free-stream value or default values.
Arguments
None
Calls
Called by
Contents
Source Code
fill_fixed_values
Source Code
    subroutine fill_fixed_values()
      !< fill the Fixed_var array with with free-stream value
      !< or default values.
      implicit none
      integer :: count
      integer :: ios=-1
      do count = 1,6
        !case ("FIX_DENSITY")
          call set_value(fixed_density , density_inf, density_inf , count, ios)
        !case ("FIX_X_SPEED")
          call set_value(fixed_x_speed , x_speed_inf, x_speed_inf , count, ios)
        !case ("FIX_Y_SPEED")
          call set_value(fixed_y_speed , y_speed_inf, y_speed_inf , count, ios)
        !case ("FIX_Z_SPEED")
          call set_value(fixed_z_speed , z_speed_inf, z_speed_inf , count, ios)
        !case ("FIX_PRESSURE")
          call set_value(fixed_pressure, pressure_inf, pressure_inf, count, ios)
        !case ("WALL_TEMPERATURE")
          call set_value(fixed_wall_temperature, 0.0, 0.0, count, ios)
        !case ("TOTAL_TEMPERATURE")
          call set_value(fixed_Ttemperature, 0.0, 0.0, count, ios)
        !case ("TOTAL_PRESSURE")
          call set_value(fixed_Tpressure, 0.0, 0.0, count, ios)
        select case (turbulence)
          case ("none")
            !do nothing
            continue
          case ("sst", 'tw', 'sst2003')
            !case ("FIX_tk")
              call set_value(fixed_tk      , tk_inf, tk_inf      , count, ios)
            !case ("FIX_tw")
              call set_value(fixed_tw      , tw_inf, tw_inf      , count, ios)
          case ("kkl")
            !case ("FIX_tk")
              call set_value(fixed_tk      , tk_inf, tk_inf      , count, ios)
            !case ("FIX_tkl")
              call set_value(fixed_tkl     , tkl_inf, tkl_inf     , count, ios)
          case ("sa", "saBC")
            !case ("FIX_tv")
              call set_value(fixed_tk      , tv_inf, tv_inf      , count, ios)
          case DEFAULT
            Fatal_error
        end select
      end do
    end subroutine fill_fixed_values
Call graph
fill_fixed_values calls set_value
read_fixed_values calls fill_fixed_values
setup_bc calls read_fixed_values
setup_solver calls setup_bc
setup_all calls setup_bc
start_run calls setup_solver
main calls start_run