find_resnorm – FEST-3D
find_resnorm Subroutine
10 statements
Source File
public subroutine find_resnorm()
Find the normalized residual for each processor
Arguments
None
Calls
Called by
Contents
Source Code
find_resnorm
Source Code
    subroutine find_resnorm()
      !< Find the normalized residual for each processor
      implicit none
      call get_absolute_resnorm()
      call collect_resnorm_from_all_blocks()
      call assemble_resnom_at_each_process()
      call get_relative_resnorm()
      if((mod(current_iter,res_write_interval)==0 .or. &
              current_iter==Res_itr .or.               &
              current_iter==1)      .and.              &
              process_id  ==0)      then
        call write_resnorm()
      end if
    end subroutine find_resnorm
Call graph
find_resnorm calls write_resnorm, collect_resnorm_from_all_blocks, get_absolute_resnorm, get_relative_resnorm, assemble_resnom_at_each_process
collect_resnorm_from_all_blocks calls mpi_allgather
iterate_one_more_time_step calls find_resnorm
main calls iterate_one_more_time_step