find_DCCVn – FEST-3D
find_DCCVn Subroutine
7 statements
Source File
public subroutine find_DCCVn()
Find gradient of the dot product between cell velocity and unit normal
Arguments
None
Calls
Called by
Contents
Source Code
find_DCCVn
Source Code
    subroutine find_DCCVn()
      !< Find gradient of the dot product between cell velocity and unit normal
      implicit none
      call find_CCVn()
      call compute_gradient(DCCVnX, dist, 'x')
      call compute_gradient(DCCVnY, dist, 'y')
      call compute_gradient(DCCVnZ, dist, 'z')
    end subroutine find_DCCVn
Call graph
find_dccvn calls compute_gradient, find_ccvn
add_sst_source_lctm2015 calls find_dccvn
add_source_term_residue calls add_sst_source_lctm2015
get_total_conservative_residue calls add_source_term_residue
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step