find_CCnormal – FEST-3D
find_CCnormal Subroutine
10 statements
Source File
private subroutine find_CCnormal()
Find the cell-center unit normal
Arguments
None
Calls
Called by
Contents
Source Code
find_CCnormal
Source Code
    subroutine find_CCnormal()
      !< Find the cell-center unit normal
      implicit none
      call compute_gradient(CCnormalX, dist, 'x')
      call compute_gradient(CCnormalY, dist, 'y')
      call compute_gradient(CCnormalZ, dist, 'z')
      !using already allocated memeory for storing magnitude
      CCVn = sqrt(CCnormalX**2 + CCnormalY**2 + CCnormalZ**2)
      !CCVn hold the magnitude of CCnormal temporaraly and can be
      !overwritten after next three lines of code.
      CCnormalX = CCnormalX/(CCVn + 1e-12)
      CCnormalY = CCnormalY/(CCVn + 1e-12)
      CCnormalZ = CCnormalZ/(CCVn + 1e-12)
    end subroutine find_CCnormal
Call graph
find_ccnormal calls compute_gradient
setupcc calls find_ccnormal
setup_solver calls setupcc
start_run calls setup_solver
main calls start_run