finish_run – FEST-3D
finish_run Subroutine
7 statements
Source File
public subroutine finish_run()
Finishing the solution computation
Arguments
None
Calls
Called by
Contents
Source Code
finish_run
Source Code
    subroutine finish_run()
      !< Finishing the solution computation
      implicit none
      integer :: ierr
      call close_all_files()
      call destroy_solver()
      call MPI_FINALIZE(ierr)
    end subroutine finish_run
Call graph
finish_run calls close_all_files, destroy_solver, mpi_finalize
close_all_files calls close_file
destroy_solver calls destroycc, destroy_time, destroy_update, destroy_gradients, destroy_grid, destroy_resnorm, destroy_scheme, destroy_state, destroy_interface, destroy_geometry, destroy_viscosity, dmsg, destroy_wall_dist, destroy_bc, destroy_source
destroycc calls dealloc, debugcall
destroy_time calls dmsg, alloc, mpi_gather, dealloc, write_time
destroy_update calls destroy_lusgs, destroy_plusgs, dealloc
destroy_gradients calls destroy_sst_grad, destroy_memory, destroy_sa_grad, destroy_kkl_grad, debugcall, destroy_laminar_grad, destroy_lctm2015_grad
destroy_grid calls dmsg, dealloc
destroy_resnorm calls close_file, deallocate_memory
destroy_state calls deallocate_memory, debugcall, unlink_aliases
destroy_interface calls dealloc
destroy_geometry calls dmsg, deallocate_memory
destroy_viscosity calls dealloc
destroy_wall_dist calls dmsg, dealloc
destroy_bc calls dealloc
main calls finish_run