get_count_within_braces – FEST-3D
get_count_within_braces Subroutine
8 statements
Source File
private subroutine get_count_within_braces(handler, count)
Get number of variables between two curly braces
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: handler
file handler from which list number is extracted
integer, intent(out) :: count
Extracted count
Calls
Called by
Contents
Source Code
get_count_within_braces
Source Code
      subroutine get_count_within_braces(handler, count)
        !< Get number of variables between two curly braces
        implicit none
        integer, intent(in) :: handler
        !< file handler from which list number is extracted
        integer, intent(out) :: count
        !< Extracted count
        integer :: skip
        ! skipping lines outside braces
        skip  = get_number_of_line('{', handler)
        ! finding actual count if any
        count = get_number_of_line('}', handler)
      end subroutine get_count_within_braces
Call graph
get_count_within_braces calls get_number_of_line
read_res_list calls get_count_within_braces
read_input_and_controls calls read_res_list
setup_solver calls read_input_and_controls
setup_all calls read_input_and_controls
start_run calls setup_solver
main calls start_run