get_rw_count – FEST-3D
get_rw_count Subroutine
48 statements
Source File
private subroutine get_rw_count()
Get read/write count
Arguments
None
Calls
Called by
Contents
Source Code
get_rw_count
Source Code
      subroutine get_rw_count()
        !< Get read/write count
        implicit none
        integer :: ios
        character(len=64) :: buf
        r_count=0
        w_count=0
        call close_file(OUTIN_FILE_UNIT)
        open(OUTIN_FILE_UNIT, file=outin_file, status='old', action='read')
        ! write list dimension
        do while(.true.)
          read(OUTIN_FILE_UNIT, *, iostat=ios) buf
          if(trim(buf)=='{') EXIT
          if(is_iostat_end(ios)) EXIT
        end do
        w_count = 0
        do while (.true.)
          read(OUTIN_FILE_UNIT, *, iostat=ios) buf
          if (trim(buf)=='}') EXIT
          if(is_iostat_end(ios)) EXIT
          w_count = w_count + 1
        end do
        if(w_count>0) then
          allocate(w_list(1:w_count))
        else
          w_count=3
          allocate(w_list(1:w_count))
          w_list(1) = "Velocity"
          w_list(2) = "Density"
          w_list(3) = "Pressure"
        end if
        ! read list dimesnion
        do while(.true.)
          read(OUTIN_FILE_UNIT, *, iostat=ios) buf
          if(trim(buf)=='{') EXIT
          if(is_iostat_end(ios)) EXIT
        end do
        r_count = 0
        do while (.true.)
          read(OUTIN_FILE_UNIT, *, iostat=ios) buf
          if (trim(buf)=='}') EXIT
          if(is_iostat_end(ios)) EXIT
          r_count = r_count + 1
        end do
        if(r_count==0) then
          allocate(r_list(1:w_count))
        else
          allocate(r_list(1:r_count))
        end if
        close(OUTIN_FILE_UNIT)
      end subroutine get_rw_count
Call graph
get_rw_count calls close_file
read_output_control calls get_rw_count
read_input_and_controls calls read_output_control
setup_solver calls read_input_and_controls
setup_all calls read_input_and_controls
start_run calls setup_solver
main calls start_run