get_number_of_line – FEST-3D
get_number_of_line Function
15 statements
Source File
private function get_number_of_line(till, infile) result(number)
Get number of lines till some character like "#"
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: till
integer, intent(in) :: infile
Return Value integer
Called by
Contents
Source Code
get_number_of_line
Source Code
      function get_number_of_line(till, infile) result(number)
        !< Get number of lines till some character like "#"
        implicit none
        integer          ,intent(in) :: infile
        character(len= 1),intent(in) :: till
        character(len=64)   :: buf
        integer             :: ios
        integer             :: number
        number=0
        do while(.true.)
          read(infile, *, iostat=ios) buf
          if(trim(buf)==till) EXIT
          if(is_iostat_end(ios)) EXIT
          number = number + 1
        end do
      end function get_number_of_line
Call graph
read_res_list calls get_number_of_line, get_count_within_braces
get_count_within_braces calls get_number_of_line
read_input_and_controls calls read_res_list
setup_solver calls read_input_and_controls
setup_all calls read_input_and_controls
start_run calls setup_solver
main calls start_run