init_infinity_values – FEST-3D
init_infinity_values Subroutine
48 statements
Source File
private subroutine init_infinity_values()
Set the values of the infinity variables "qp_inf"
Arguments
None
Calls
Called by
Contents
Source Code
init_infinity_values
Source Code
        subroutine init_infinity_values()
            !< Set the values of the infinity variables "qp_inf"
            !-----------------------------------------------------------
            implicit none
            DebugCall("init_infinity_values")
            density_inf = free_stream_density
            x_speed_inf = free_stream_x_speed
            y_speed_inf = free_stream_y_speed
            z_speed_inf = free_stream_z_speed
            pressure_inf = free_stream_pressure
            vel_mag = sqrt(x_speed_inf**2 + y_speed_inf**2 + z_speed_inf**2)
            MInf    = Vel_mag/sqrt(gm*pressure_inf/density_inf)
            Reynolds_number = density_inf*vel_mag*1.0/mu_ref
            Turb_intensity_inf = free_stream_tu/100
            select case (trim(turbulence))
                case ("none")
                    continue
                case ("sst", "sst2003", "bsl")
                    tk_inf = 1.5*((Vel_mag*Turb_Intensity_inf)**2)
                    tw_inf = density_inf*tk_inf/(mu_ref*mu_ratio_inf)
                case ("kkl")
                    tk_inf = 9*(1e-9)*(sound_speed_inf()**2)
                    tkl_inf = 1.5589*(1e-6)*(mu_ref*sound_speed_inf())/density_inf
                case ("sa")
                     tv_inf = mu_ratio_inf*mu_ref/density_inf
                case ("saBC")
                    tv_inf = 0.005*mu_ratio_inf*mu_ref/density_inf
                case ("kw")
                    tk_inf = 1.5*((Vel_mag*Turb_Intensity_inf)**2)
                    tw_inf = density_inf*tk_inf/(mu_ref*mu_ratio_inf)
                case ("ke")
                    tk_inf = 1.5*((Vel_mag*Turb_Intensity_inf)**2)
                    tw_inf = 0.09*density_inf*tk_inf*tk_inf/(mu_ref*mu_ratio_inf)
                case ("des-sst")
                    tk_inf = 1.5*((Vel_mag*Turb_Intensity_inf)**2)
                    tw_inf = density_inf*tk_inf/(mu_ref*mu_ratio_inf)
                case ("les")
                  continue
                  ! todo
                case DEFAULT
                  Fatal_error
            end select
            !Transition modeling
            select case(trim(transition))
              case('lctm2015')
                tgm_inf = free_stream_tgm
              case('bc', 'none')
                !do nothing
                continue
              case DEFAULT
                Fatal_error
            end Select
        end subroutine init_infinity_values
Call graph
init_infinity_values calls sound_speed_inf, debugcall
setup_state calls init_infinity_values
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run