init_state_with_infinity_values – FEST-3D
init_state_with_infinity_values Subroutine
8 statements
Source File
private subroutine init_state_with_infinity_values()
Initialize the state based on the infinity values.
Arguments
None
Calls
Called by
Contents
Source Code
init_state_with_infinity_values
Source Code
        subroutine init_state_with_infinity_values()
            !< Initialize the state based on the infinity values.
            !-----------------------------------------------------------
            implicit none
            integer :: i
            DebugCall("init_state_with_infinity_values")
            do i = 1,n_var
                qp(:, :, :, i) = qp_inf(i)
            end do
        end subroutine init_state_with_infinity_values
Call graph
init_state_with_infinity_values calls debugcall
initstate calls init_state_with_infinity_values
setup_state calls initstate
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run