iterate_one_more_time_step – FEST-3D
iterate_one_more_time_step Subroutine
19 statements
Source File
public subroutine iterate_one_more_time_step()
Perform one time step iteration
Arguments
None
Calls
Called by
Contents
Source Code
iterate_one_more_time_step
Source Code
        subroutine iterate_one_more_time_step()
            !< Perform one time step iteration
            !  This subroutine performs one iteration by stepping through
            !  time once.
            !-----------------------------------------------------------
            implicit none
            integer :: ierr
            DebugCall('iterate_one_more_time_step')
            if (process_id==0) then
              print*, control%current_iter
            end if
            call get_next_solution(qp, Temp, residue, delta_t, cells, F,G,H, Ifaces,Jfaces,Kfaces,control, schemes, flow, boundary, dims)
            call find_resnorm(files%RESNORM_FILE_UNIT, residue, F,G,H, control, schemes, dims)
            call checkpoint(files, qp, nodes, control, schemes, dims)
            control%current_iter = control%current_iter + 1
            if(process_id==0)then
              open(files%STOP_FILE_UNIT, file=files%stop_file)
              read(files%STOP_FILE_UNIT,*) control%want_to_stop
              close(files%STOP_FILE_UNIT)
            end if
            call MPI_BCAST(control%want_to_stop,1,MPI_INTEGER,0,MPI_COMM_WORLD,ierr)
            if (control%want_to_stop==1) control%Halt = .TRUE.
        end subroutine iterate_one_more_time_step
Call graph
iterate_one_more_time_step calls find_resnorm, checkpoint, debugcall, get_next_solution, mpi_bcast
find_resnorm calls assemble_resnom_at_each_process, write_resnorm, get_relative_resnorm, collect_resnorm_from_all_blocks, get_absolute_resnorm
checkpoint calls debugcall, make_dump_dir, dump_data, purge_dump_dir
get_next_solution calls update_with, compute_time_step, update_with_plusgs, update_with_lusgs, get_total_conservative_residue
make_dump_dir calls create_directory
compute_time_step calls debugcall, compute_local_time_step, compute_global_time_step, update_simulation_clock
update_with_plusgs calls update_lctm2015, update_laminar_variables, update_sa_variables, update_sst_variables
dump_data calls debugcall, write_file, write_restart_log
collect_resnorm_from_all_blocks calls mpi_allgather
purge_dump_dir calls remove_directory
update_with_lusgs calls debugcall, update_kkl_variables, update_sa_variables, update_lctm2015, update_laminar_variables, update_sst_variables
get_total_conservative_residue calls apply_interface, add_source_term_residue, compute_residue, populate_ghost_primitive, evaluate_all_gradients, calculate_viscosity, reconstruct_boundary_state, compute_fluxes, compute_face_interpolant, compute_viscous_fluxes
main calls iterate_one_more_time_step