lcase – FEST-3D
lcase Function
10 statements
Source File
public function lcase(text) result(res)
make the whole string to lower case
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: text
Input string of any case
Return Value character(len=STRING_BUFFER_LENGTH)
output string of lower case
Called by
Contents
Source Code
lcase
Source Code
    function lcase(text) result(res)
      !< make the whole string to lower case
      CHARACTER(len=*), intent(in)         :: text
      !< Input string of any case
      character(len=STRING_BUFFER_LENGTH) :: res
      !< output string of lower case
      integer ::  I,C
      res=text
      DO I = 1,LEN(TEXT)
        C = INDEX("ABCDEFGHIJKLMNOPQRSTUVWXYZ",TEXT(I:I))
        IF (C.GT.0) res(I:I) = "abcdefghijklmnopqrstuvwxyz"(C:C)
      END DO
    end function lcase
Call graph
verify_write_control calls lcase
verify_read_control calls lcase
initstate calls verify_write_control, read_file
read_file calls verify_read_control
setup_state calls initstate
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run