oct_to_int8 – FEST-3D
oct_to_int8 Subroutine
14 statements
Source File
public subroutine oct_to_int8(r, octstr)
String of octal number converted to integer of kind 8
Arguments
Type Intent Optional Attributes Name
integer(kind=8), intent(out) :: r
character(len=*) :: octstr
Called by
Contents
Source Code
oct_to_int8
Source Code
        subroutine oct_to_int8(r, octstr)
          !< String of octal number converted to integer of kind 8
            implicit none
            character(len=*) :: octstr
            integer(kind=8), intent(out) :: r
            integer :: current_digit
            integer :: i
            i = len(octstr)
            r = 0
            do while (i > 0)
                read (octstr(i:i), *) current_digit
                r = r + ((8 ** (len(octstr) - i)) * current_digit)
                i = i - 1
            end do
        end subroutine oct_to_int8
Call graph
oct2int calls oct_to_int8
int4_from_string calls oct2int
int8_from_string calls oct2int
assignment(=) calls int4_from_string, int8_from_string