open_file – FEST-3D
open_file Subroutine
8 statements
Source File
private subroutine open_file(filename)
Open file from the restart folder
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Calls
Called by
Contents
Source Code
open_file
Source Code
    subroutine open_file(filename)
      !< Open file from the restart folder
      implicit none
      character(len=*), intent(in) :: filename
      call dmsg(1, 'read_output_vtk', 'open_file')
      write(restartfile, '(A,I4.4,A,I2.2)') 'time_directories/',start_from,&
                          '/restart/process_', process_id
      open(IN_FILE_UNIT, file=trim(filename)//trim(file_format))!, form=trim(data_format))
      open(RESTART_FILE_UNIT, file=restartfile, status='old')
    end subroutine open_file
Call graph
open_file calls dmsg
read_file calls open_file
initstate calls read_file
setup_state calls initstate
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run