open_file – FEST-3D
open_file Subroutine
6 statements
Source File
private subroutine open_file(filename)
Open the file to write the solution
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Calls
Called by
Contents
Source Code
open_file
Source Code
    subroutine open_file(filename)
      !< Open the file to write the solution
      implicit none
      character(len=*), intent(in) :: filename
      call dmsg(1, 'write_output_vtk', 'open_file')
      open(OUT_FILE_UNIT, file=trim(filename)//trim(file_format) + '.part', form=trim(data_format))
    end subroutine open_file
Call graph
open_file calls dmsg
write_file calls open_file
dump_data calls write_file
checkpoint calls dump_data
setup_solver calls checkpoint
iterate_one_more_time_step calls checkpoint
main calls iterate_one_more_time_step, start_run
start_run calls setup_solver