populate_grid_points – FEST-3D
populate_grid_points Subroutine
22 statements
Source File
private subroutine populate_grid_points()
Use the grid file to populate the grid points.
Arguments
None
Calls
Called by
Contents
Source Code
populate_grid_points
Source Code
        subroutine populate_grid_points()
            !< Use the grid file to populate the grid points.
            !-----------------------------------------------------------
            implicit none
            character(len=STRING_BUFFER_LENGTH) :: line
            integer :: i, j, k
            integer :: ios  ! io status
            call dmsg(1, 'grid', 'populate_grid_point')
         !  print *, imx, jmx, kmx
            ! Read grid points from the grid file
            do k = 1, kmx
                do j = 1, jmx
                    do i = 1, imx
                        read(GRID_FILE_UNIT, '(A)', iostat=ios) line
                        if (ios /= 0) then
                            print *, 'Error while reading grid line.'
                            print *, 'Current grid point: ', i, j, k
                            print *, 'Current buffer length is set to: ', &
                                     STRING_BUFFER_LENGTH
                            print *, 'Exiting program.'
                            stop
                        end if
                        call extract_grid_point(line, i, j, k)
                    end do
                end do
            end do
        end subroutine populate_grid_points
Call graph
populate_grid_points calls dmsg, extract_grid_point
extract_grid_point calls dmsg
setup_grid calls populate_grid_points
setup_solver calls setup_grid
setup_all calls setup_grid
start_run calls setup_solver
main calls start_run