read_output_control – FEST-3D
read_output_control Subroutine
29 statements
Source File
private subroutine read_output_control()
read output_contorl.md file
Arguments
None
Calls
Called by
Contents
Source Code
read_output_control
Source Code
      subroutine read_output_control()
        !< read output_contorl.md file
        implicit none
        integer           :: i
        character(len=64) :: buf
        integer :: ios
        call get_rw_count()
        call close_file(OUTIN_FILE_UNIT)
        open(OUTIN_FILE_UNIT, file=outin_file, status='old', action='read')
        ! variables to write
        do while(.true.)
          read(OUTIN_FILE_UNIT, *, iostat=ios) buf
          if(trim(buf)=='{') EXIT
          if(is_iostat_end(ios)) EXIT
        end do
        do i = 1,w_count
          read(OUTIN_FILE_UNIT, *) buf
          read(buf,*) w_list(i)
        end do
        ! restart variables to read
        do while(.true.)
          read(OUTIN_FILE_UNIT, *, iostat=ios) buf
          if(trim(buf)=='{') EXIT
          if(is_iostat_end(ios)) EXIT
        end do
        do i = 1,r_count
          read(OUTIN_FILE_UNIT, *) buf
          read(buf,*) r_list(i)
        end do
        if(r_count==0) r_list=w_list
        close(OUTIN_FILE_UNIT)
      end subroutine read_output_control
Call graph
read_output_control calls close_file, get_rw_count
get_rw_count calls close_file
read_input_and_controls calls read_output_control
setup_solver calls read_input_and_controls
setup_all calls read_input_and_controls
start_run calls setup_solver
main calls start_run