read_controls – FEST-3D
read_controls Subroutine
49 statements
Source File
private subroutine read_controls()
read control.md file
Arguments
None
Calls
Called by
Contents
Source Code
read_controls
Source Code
      subroutine read_controls()
        !< read control.md file
        !---------------------------------------------
        implicit none
        character(len=STRING_BUFFER_LENGTH) :: buf
        DebugCall('read_controls')
        open(CONTROL_FILE_UNIT, file=control_file, status='old', action='read')
        !ignoring file header
        read(CONTROL_FILE_UNIT,*)
        read(CONTROL_FILE_UNIT,*)
        read(CONTROL_FILE_UNIT,*)
        ! READ CFL
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) CFL
        DebugInfo("CFL = "//trim(buf))
        ! READ start_from
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) start_from
        DebugInfo('Start from  level = '//trim(buf))
        ! READ max_iters
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) max_iters
        DebugInfo('Stop at iteration = '//trim(buf))
        ! READ checkpoint_iter
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) checkpoint_iter
        DebugInfo(' Solution write interval = '//trim(buf))
        ! READ write_file_format
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) write_file_format
        DebugInfo('Solution file format  = '//trim(buf))
        ! READ write_data_format
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) write_data_format
        DebugInfo('solution file data format = '//trim(buf))
        ! READ read_file_format
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) read_file_format
        DebugInfo('Restart file format  = '//trim(buf))
        ! READ_read data_format
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) read_data_format
        DebugInfo('Restart file data format = '//trim(buf))
        ! READ write_percision
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) write_percision
        DebugInfo('File write percision = '//trim(buf))
        ! READ purge_write
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) purge_write
        DebugInfo('Purge folder more then  = '//trim(buf))
        ! READ res_write_interval
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) res_write_interval
        DebugInfo('resnorm write interval  = '//trim(buf))
        ! READ tolerance
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) tolerance, tolerance_type
        DebugInfo(trim(tolerance_type)//' Tolerance  = '//trim(buf))
        ! READ DEBUG_LEVEL
        call get_next_token(CONTROL_FILE_UNIT, buf)
        read(buf, *) DEBUG_LEVEL
        DebugInfo('DEBUG_LEVEL = '//trim(buf))
        close(CONTROL_FILE_UNIT)
      end subroutine read_controls
Call graph
read_controls calls debuginfo, debugcall, get_next_token
read_input_and_controls calls read_controls
setup_solver calls read_input_and_controls
setup_all calls read_input_and_controls
start_run calls setup_solver
main calls start_run