read_flow – FEST-3D
read_flow Subroutine
58 statements
Source File
private subroutine read_flow()
Read flow.md control file
Arguments
None
Calls
Called by
Contents
Source Code
read_flow
Source Code
      subroutine read_flow()
        !< Read flow.md control file
        !--------------------------------------------
        implicit none
        character(len=STRING_BUFFER_LENGTH) :: buf
        DebugCall('read_flow')
        open(FLOW_FILE_UNIT, file=flow_file, status='old', action='read')
        ! ignoring file header
        read(FLOW_FILE_UNIT,*)
        read(FLOW_FILE_UNIT,*)
        read(FLOW_FILE_UNIT,*)
        ! read number of variable
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) n_var
        DebugInfo('Number of variables = '//trim(buf))
        ! read rho_inf
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) free_stream_density
        DebugInfo('free_stream_density = '//trim(buf))
        ! read u_inf
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) free_stream_x_speed
        DebugInfo('free_stream_x_speed = '//trim(buf))
        ! read v_inf
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) free_stream_y_speed
        DebugInfo('free_stream_y_speed = '//trim(buf))
        ! read w_inf
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) free_stream_z_speed
        DebugInfo('free_stream_z_speed = '//trim(buf))
        ! read P_inf
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) free_stream_pressure
        DebugInfo('free_stream_pressure = '//trim(buf))
        ! read turbulence intensity in percentage
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) free_stream_tu
        DebugInfo('free_stream_Turb_intensity = '//trim(buf))
        ! read viscosity ratio
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) mu_ratio_inf
        DebugInfo('free_stream_mu_ratio = '//trim(buf))
        ! read intermittency
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) free_stream_tgm
        DebugInfo('free_stream_Intermittency = '//trim(buf))
        ! read reference viscosity
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) mu_ref
        DebugInfo('mu_reference = '//trim(buf))
        ! Type of variation for viscosity
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) mu_variation
        DebugInfo('mu_variation = '//trim(buf))
        ! read T_red
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) T_ref
        DebugInfo('T_reference = '//trim(buf))
        ! read Sutherland temp
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) Sutherland_temp
        DebugInfo('Sutherland temperature = '//trim(buf))
        ! read prandtl number
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) Pr, tPr
        DebugInfo('Prandtl Number = '//trim(buf))
        ! read gamma
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) gm
        DebugInfo('gamma = '//trim(buf))
        ! read universal gas constant
        call get_next_token(FLOW_FILE_UNIT, buf)
        read(buf, *) R_gas
        DebugInfo('R_gas = '//trim(buf))
        close(FLOW_FILE_UNIT)
      end subroutine read_flow
Call graph
read_flow calls debuginfo, debugcall, get_next_token
get_next_token calls dmsg
read_input_and_controls calls read_flow
setup_solver calls read_input_and_controls
setup_all calls read_input_and_controls
start_run calls setup_solver
main calls start_run