read_file – FEST-3D
read_file Subroutine
21 statements
Source File
public subroutine read_file(files, qp, control, scheme, dims)
Read restart file
Arguments
Type Intent Optional Attributes Name
type(filetype), intent(inout) :: files
real(kind=wp), intent(inout), dimension(-2:dims%imx+2, -2:dims%jmx+2, -2:dims%kmx+2, 1:dims%n_var), target :: qp
type(controltype), intent(inout) :: control
type(schemetype), intent(in) :: scheme
type(extent), intent(in) :: dims
Calls
Called by
Contents
Source Code
read_file
Source Code
    subroutine read_file(files, qp, control, scheme, dims)
      !< Read restart file
      implicit none
      type(filetype), intent(inout) :: files
      type(extent), intent(in) :: dims
      type(controltype), intent(inout) :: control
      type(schemetype) , intent(in) :: scheme
      real(wp), dimension(-2:dims%imx+2, -2:dims%jmx+2, -2:dims%kmx+2, 1:dims%n_var), intent(inout), target :: qp
      call setup_file(control)
      call open_file(files,  control)
      call read_restart_file(files%RESTART_FILE_UNIT, control)
      call verify_read_control(control, scheme)
      select case (control%read_file_format)
        case ('vtk')
          call read_file_vtk(files%IN_FILE_UNIT, qp, control, scheme, dims)
        case ('tecplot')
          call read_file_tec(files%IN_FILE_UNIT, qp, control, scheme, dims)
        case DEFAULT
          Fatal_error
      end select
      call close_file(files)
    end subroutine read_file
Call graph
read_file calls verify_read_control, read_file_tec, open_file, read_restart_file, close_file, read_file_vtk, setup_file
verify_read_control calls lcase
open_file calls debugcall
close_file calls debugcall
setup_file calls debugcall
initstate calls read_file
setup_state calls initstate
setup_solver calls setup_state
start_run calls setup_solver
main calls start_run