read_input_and_controls – FEST-3D
read_input_and_controls Subroutine
12 statements
Source File
public subroutine read_input_and_controls(files, control, scheme, flow)
Read all the input control files
Arguments
Type Intent Optional Attributes Name
type(filetype), intent(in) :: files
type(controltype), intent(inout) :: control
type(schemetype), intent(inout) :: scheme
type(flowtype), intent(inout) :: flow
Calls
Called by
Contents
Source Code
read_input_and_controls
Source Code
      subroutine read_input_and_controls(files, control, scheme, flow)
        !< Read all the input control files
        implicit none
        type(filetype), intent(in) :: files
        type(controltype), intent(inout) :: control
        type(schemetype), intent(inout) :: scheme
        type(flowtype), intent(inout) :: flow
        call read_controls(files, control)
        call read_scheme(files, scheme)
        call read_flow(files, control, flow)
        call read_output_control(files, control)
        call read_Res_list(files, control)
      end subroutine read_input_and_controls
Call graph
read_input_and_controls calls read_output_control, read_controls, read_res_list, read_scheme, read_flow
read_output_control calls get_rw_count
read_controls calls debuginfo, get_next_token, debugcall
read_res_list calls get_count_within_braces, get_number_of_line
read_scheme calls debuginfo, get_next_token, debugcall
read_flow calls debuginfo, get_next_token, debugcall
get_count_within_braces calls get_number_of_line
setup_solver calls read_input_and_controls
start_run calls setup_solver
main calls start_run