real_to_str – FEST-3D
real_to_str Function
29 statements
Source File
public function real_to_str(r) result(a)
Convert real number to string
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: r
Return Value character(len=MAX_STRING_LEN)
Called by
Contents
None
Call graph
tostr calls real_to_str
reallen calls real_to_str
str_cat_real calls tostr
intlen calls tostr
real_cat_str calls tostr
len calls reallen, intlen
operator( + ) calls str_cat_real, real_cat_str