reconstruct_imax – FEST-3D
reconstruct_imax Subroutine
36 statements
Source File
private subroutine reconstruct_imax()
Reconstruct state at the IMAX boundary face with MUSCL scheme
Arguments
None
Calls
Called by
Contents
Source Code
reconstruct_imax
Source Code
    subroutine reconstruct_imax()
      !< Reconstruct state at the IMAX boundary face with MUSCL scheme
      implicit none
      integer :: i, j, k, l
      real :: psi1, psi2, fd, bd, r
      real :: kappa, phi
      phi = 1.0
      kappa = 1./3.
      switch_L=ilimiter_switch
      if (ppm_flag==1) then
        do l = 1, n_var
          if(l>=6) switch_L=itlimiter_switch
         do k = 1, kmx - 1
          do j = 1, jmx - 1
           do i = imx-1, imx-1
             fd = qp(i+1, j, k, l) - qp(i  , j, k, l)
             bd = qp(i  , j, k, l) - qp(i-1, j, k, l)
             r = fd / bd
             psi1 = max(0., min(2*r, (2 + r)/3., 2.))
             psi1 = (1 - (1 - psi1)*switch_L )
             r = bd / fd
             psi2 = max(0., min(2*r, (2 + r)/3., 2.))
             psi2 = (1 - (1 - psi2)*switch_L )
             ! right face of last interior cell
             x_qp_left(i+1, j, k, l) = qp(i, j, k, l) + 0.25*phi* &
                 (((1.-kappa) * psi1 * bd) + ((1.+kappa) * psi2 * fd))
             ! left face of last interior cell
             x_qp_right(i, j, k, l) = qp(i, j, k, l) - 0.25*phi* &
                 (((1.+kappa) * psi1 * bd) + ((1.-kappa) * psi2 * fd))
           end do
          end do
         end do
        end do
      end if
      if(imax_id==-8 .or. imax_id==-9)then
         x_qp_left(imx,1:jmx-1,1:kmx-1,1:n_var) = qp(imx,1:jmx-1,1:kmx-1,1:n_var)
        x_qp_right(imx,1:jmx-1,1:kmx-1,1:n_var) = qp(imx,1:jmx-1,1:kmx-1,1:n_var)
      else
        x_qp_right(imx,1:jmx-1,1:kmx-1,1:n_var)  = 0.5*(qp(imx-1,1:jmx-1,1:kmx-1,1:n_var)&
                                                       +qp(imx  ,1:jmx-1,1:kmx-1,1:n_var))
      end if
    end subroutine reconstruct_imax
Call graph
reconstruct_imax calls x_qp_right, x_qp_left
reconstruct_boundary_state calls reconstruct_imax
get_total_conservative_residue calls reconstruct_boundary_state
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step