set_value – FEST-3D
set_value Subroutine
13 statements
Source File
private subroutine set_value(fixed_var, fix_val, inf_val, count, ios)
Set particular value to the Fixed_var variable
Arguments
Type Intent Optional Attributes Name
real, intent(out), dimension(:) :: fixed_var
real, intent(in) :: fix_val
real, intent(in) :: inf_val
integer, intent(in) :: count
integer, intent(in) :: ios
Called by
Contents
Source Code
set_value
Source Code
    subroutine set_value(fixed_var, fix_val, inf_val, count, ios)
      !< Set particular value to the Fixed_var variable
      implicit none
      integer, intent(in) :: ios
      integer, intent(in) :: count
      real   , intent(in) :: fix_val
      real   , intent(in) :: inf_val
      real   , intent(out), dimension(:) :: fixed_var
      if(ios==0)then
        fixed_var(count) = fix_val
      else
        fixed_var(count) = inf_val
      end if
    end subroutine set_value
Call graph
fill_fixed_values calls set_value
get_fixed_values calls set_value
read_fixed_values calls fill_fixed_values, get_fixed_values
setup_bc calls read_fixed_values
setup_solver calls setup_bc
setup_all calls setup_bc
start_run calls setup_solver
main calls start_run