set_n_var_value – FEST-3D
set_n_var_value Subroutine
22 statements
Source File
private subroutine set_n_var_value()
Set number of variable to solver for based on the tubulence and transition model being used.
Arguments
None
Calls
Called by
Contents
Source Code
set_n_var_value
Source Code
        subroutine set_n_var_value()
          !< Set number of variable to solver for based on
          !< the tubulence and transition model being used.
          implicit none
          DebugCall("set_n_var_value")
          select case (trim(turbulence))
            case('none')
              n_var=5
            case('sa', 'saBC')
              n_var=6
            case('sst', "sst2003", 'bsl', 'kw', 'ke', 'kkl', 'Des-kw')
              n_var=7
            case DEFAULT
              n_var=5
          end select
          !Transition modeling
          select case(trim(transition))
            case('lctm2015')
              n_var = n_var + 1
            case('bc', 'none')
              n_var = n_var + 0
            case DEFAULT
              Fatal_error
          end Select
        end subroutine set_n_var_value
Call graph
set_n_var_value calls debugcall
setup_state calls set_n_var_value
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run