setup_plusgs – FEST-3D
setup_plusgs Subroutine
35 statements
Source File
public subroutine setup_plusgs()
Allocate array memory for data communication
Arguments
None
Calls
Called by
Contents
Source Code
setup_plusgs
Source Code
    subroutine setup_plusgs()
      !< Allocate array memory for data communication
      implicit none
      character(len=*), parameter :: &
        errmsg="module: LUSGS, subrouinte setup"
      ibuf_size = (jmx-1)*(kmx-1)*n_var*1
      jbuf_size = (imx-1)*(kmx-1)*n_var*1
      kbuf_size = (imx-1)*(jmx-1)*n_var*1
      call alloc(imin_send_buf,1,ibuf_size, errmsg)
      call alloc(jmin_send_buf,1,jbuf_size, errmsg)
      call alloc(kmin_send_buf,1,kbuf_size, errmsg)
      call alloc(imin_recv_buf,1,ibuf_size, errmsg)
      call alloc(jmin_recv_buf,1,jbuf_size, errmsg)
      call alloc(kmin_recv_buf,1,kbuf_size, errmsg)
      call alloc(imax_send_buf,1,ibuf_size, errmsg)
      call alloc(jmax_send_buf,1,jbuf_size, errmsg)
      call alloc(kmax_send_buf,1,kbuf_size, errmsg)
      call alloc(imax_recv_buf,1,ibuf_size, errmsg)
      call alloc(jmax_recv_buf,1,jbuf_size, errmsg)
      call alloc(kmax_recv_buf,1,kbuf_size, errmsg)
      call alloc(delQ, 0, imx, 0, jmx, 0, kmx, 1, n_var)
      call alloc(delQstar, 0, imx, 0, jmx, 0, kmx, 1, n_var)
      if(mu_ref==0.0 .or. turbulence=='none') then
        call alloc(dummy, 0, imx, 0, jmx, 0, kmx)
        dummy = 0.0
      end if
      if(mu_ref==0.0)then
        mmu => dummy
      else
        mmu => mu
      end if
      if(trim(turbulence)=='none')then
        tmu => dummy
      else
        tmu => mu_t
      end if
    end subroutine setup_plusgs
Call graph
setup_plusgs calls alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_update calls setup_plusgs
setup_solver calls setup_update
start_run calls setup_solver
main calls start_run