setup_wall_dist – FEST-3D
setup_wall_dist Subroutine
15 statements
Source File
public subroutine setup_wall_dist(files, dims)
Allocate memory to the wall_distance variables and read the surface node file
Arguments
Type Intent Optional Attributes Name
type(filetype), intent(in) :: files
type(extent), intent(in) :: dims
Calls
Called by
Contents
Source Code
setup_wall_dist
Source Code
    subroutine setup_wall_dist(files, dims)
      !< Allocate memory to the wall_distance variables
      !< and read the surface node file
      implicit none
      type(filetype), intent(in) :: files
      type(extent), intent(in) :: dims
      imx = dims%imx
      jmx = dims%jmx
      kmx = dims%kmx
      DebugCall('setup_wall_dist')
      call setup_nodefile(files)
      call alloc(wall_x, 1, n_surfnodes,&
                "ERROR: unale to allocate memory to 'Dist' variable " )
      call alloc(wall_y, 1, n_surfnodes,&
                "ERROR: unale to allocate memory to 'Dist' variable " )
      call alloc(wall_z, 1, n_surfnodes,&
                "ERROR: unale to allocate memory to 'Dist' variable " )
      call alloc(dist, -2, imx+2, -2, jmx+2, -2, kmx+2, &
                "ERROR: unale to allocate memory to 'Dist' variable " )
      call read_destroy_nodefile(files)
    end subroutine setup_wall_dist
Call graph
setup_wall_dist calls debugcall, alloc, read_destroy_nodefile, setup_nodefile
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_solver calls setup_wall_dist
start_run calls setup_solver
main calls start_run