setup_lctm2015_grad – FEST-3D
setup_lctm2015_grad Subroutine
14 statements
Source File
public subroutine setup_lctm2015_grad()
setup Pointer to the main array which stores gradient all variables with x, y, z
Arguments
None
Calls
Called by
Contents
Source Code
setup_lctm2015_grad
Source Code
    subroutine setup_lctm2015_grad()
      !< setup Pointer to the main array which stores gradient
      !< all variables with x, y, z
      implicit none
      DebugCall('setup_sst_grad')
      select case(trim(transition))
        case('lctm2015')
          gradtgm_x(0:imx, 0:jmx, 0:kmx) => gradqp_x(:, :, :, n_grad)
          gradtgm_y(0:imx, 0:jmx, 0:kmx) => gradqp_y(:, :, :, n_grad)
          gradtgm_z(0:imx, 0:jmx, 0:kmx) => gradqp_z(:, :, :, n_grad)
        case( 'bc', 'none')
          !do nothing
          continue
        case DEFAULT
          Fatal_error
      end Select
    end subroutine setup_lctm2015_grad
Call graph
setup_lctm2015_grad calls debugcall
setup_gradients calls setup_lctm2015_grad
setup_solver calls setup_gradients
setup_all calls setup_gradients
start_run calls setup_solver
main calls start_run