setup_grid – FEST-3D
setup_grid Subroutine
12 statements
Source File
public subroutine setup_grid(gridfile)
Read the grid file and initialize the grid
Arguments
Type Intent Optional Attributes Name
character(len=64), intent(in) :: gridfile
Calls
Called by
Contents
Source Code
setup_grid
Source Code
        subroutine setup_grid(gridfile)
            !< Read the grid file and initialize the grid
            !-----------------------------------------------------------
            implicit none
            character(len=64), intent(in) :: gridfile
   !        character(len=32) :: sphindfile
            call dmsg(1, 'grid', 'setup_grid')
!           sphindfile = 'sphere-indices.txt'
            open(GRID_FILE_UNIT, file=gridfile)
!           open(SPHERE_INDICES_FILE_UNIT, file=sphindfile)
            call extract_grid_size()
!           call extract_sphere_indices_size()
            call allocate_memory()
            !read interface mapping
            call read_interface_map()
            ! ghost grid exchange
            call populate_grid_points()
!           call populate_sphere_indices()
            close(GRID_FILE_UNIT)
!           close(SPHERE_INDICES_FILE_UNIT)
            ! populate ghost grid points
            call ghost_grid()
        end subroutine setup_grid
Call graph
setup_grid calls dmsg, allocate_memory, ghost_grid, extract_grid_size, read_interface_map, populate_grid_points
allocate_memory calls dmsg, alloc
ghost_grid calls dmsg, mpi_recv, mpi_barrier, mpi_send
extract_grid_size calls dmsg
read_interface_map calls close_file, read_periodic_bc_file, change_map_to_particular_range
populate_grid_points calls dmsg, extract_grid_point
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
extract_grid_point calls dmsg
setup_solver calls setup_grid
setup_all calls setup_grid
start_run calls setup_solver
main calls start_run