setup_solver – FEST-3D
setup_solver Subroutine
33 statements
Source File
public subroutine setup_solver()
Call to allocate memoery and initialize domain
Arguments
None
Calls
Called by
Contents
Source Code
setup_solver
Source Code
        subroutine setup_solver()
          !< Call to allocate memoery and initialize domain
          !--------------------------------------------------
            implicit none
            integer :: ierr
            DebugCall('setup_solver: Start')
            call get_process_data(control) ! parallel calls
            call read_layout_file(files, control, boundary) ! reads layout file calls
            call read_input_and_controls(files, control, schemes, flow)
            call setup_grid(files, nodes, control, boundary, dims)
            call setup_geometry(cells, Ifaces, Jfaces, Kfaces, nodes, boundary, dims)
            !call setup_viscosity(mu, mu_t, schemes, flow, dims)
            call setup_viscosity(schemes, flow, dims)
            call setup_state(files, qp, control, schemes, flow, dims)
            allocate(Temp(-2:dims%imx+2,-2:dims%jmx+2,-2:dims%kmx+2))
            call setup_gradients(control,schemes,flow,dims)
            !call setup_source
            call setup_bc(files, schemes, flow, boundary, dims)
            call setup_time(delta_t, control,dims)
            call setup_update(control,schemes,flow, dims)
            call setup_interface(control,dims)
            call setup_scheme(residue, F,G,H, control, dims)
            if(schemes%turbulence /= 'none') then
              call write_surfnode(files, nodes, control, boundary, dims)
              call setup_wall_dist(files, dims)
              call mpi_barrier(MPI_COMM_WORLD,ierr)
              call find_wall_dist(nodes, dims)
            end if
            call setupCC(schemes, cells, Ifaces,Jfaces,Kfaces, dims)
            call setup_resnorm(files, control, schemes, flow)
            call initmisc()
            control%checkpoint_iter_count = 0
            call checkpoint(files, qp, nodes, control, schemes, dims)  ! Create an initial dump file
            control%current_iter=1
            DebugCall('setup_solver: checkpoint')
            DebugCall('Setup solver complete')
        end subroutine setup_solver
Call graph
setup_solver calls initmisc, mpi_barrier, setup_geometry, setup_time, setup_gradients, checkpoint, setupcc, setup_state, setup_scheme, find_wall_dist, setup_wall_dist, debugcall, write_surfnode, read_input_and_controls, setup_interface, setup_bc, setup_resnorm, setup_viscosity, get_process_data, setup_update, read_layout_file, setup_grid
start_run calls setup_solver
main calls start_run