setupCC – FEST-3D
setupCC Subroutine
14 statements
Source File
public subroutine setupCC()
Allocate memory for the cell center variable only in case of transition model
Arguments
None
Calls
Called by
Contents
Source Code
setupCC
Source Code
    subroutine setupCC()
      !< Allocate memory for the cell center variable only in case of transition model
      implicit none
      DebugCall("Setup CC")
      if((transition=='lctm2015') .and. turbulence/='none')then
        call alloc(CCnormalX, -2, imx+2, -2, jmx+2, -2, kmx+2, AErrMsg("CCnormalX"))
        call alloc(CCnormalY, -2, imx+2, -2, jmx+2, -2, kmx+2, AErrMsg("CCnormalY"))
        call alloc(CCnormalZ, -2, imx+2, -2, jmx+2, -2, kmx+2, AErrMsg("CCnormalZ"))
        call alloc(CCVn,   -2, imx+2, -2, jmx+2, -2, kmx+2, AErrMsg("CCVn"))
        call alloc(DCCVnX, -2, imx+2, -2, jmx+2, -2, kmx+2, AErrMsg("DCCVnZ"))
        call alloc(DCCVnY, -2, imx+2, -2, jmx+2, -2, kmx+2, AErrMsg("DCCVnY"))
        call alloc(DCCVnZ, -2, imx+2, -2, jmx+2, -2, kmx+2, AErrMsg("DCCVnZ"))
        call find_CCnormal()
      end if
    end subroutine setupCC
Call graph
setupcc calls alloc, debugcall, aerrmsg, find_ccnormal
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
find_ccnormal calls compute_gradient
setup_solver calls setupcc
start_run calls setup_solver
main calls start_run