setup_viscosity – FEST-3D
setup_viscosity Subroutine
23 statements
Source File
public subroutine setup_viscosity()
allocate and pointer for molecular and turbulent viscosity
Arguments
None
Calls
Called by
Contents
Source Code
setup_viscosity
Source Code
    subroutine setup_viscosity()
      !< allocate and pointer for molecular and turbulent viscosity
      !setup_molecular_viscosity()
      if (mu_ref/=0.) then
        call alloc(mu, -2, imx+2, -2, jmx+2, -2, kmx+2)
        mu = mu_ref !intialize
      end if
      !--- setup_turbulent_viscosity ---!
      if (turbulence/='none') then
        call alloc(mu_t, -2,imx+2, -2,jmx+2, -2,kmx+2)
        select case (trim(turbulence))
          case ('none')
            !do nothing
            continue
          case ('sa', 'saBC')
            sa_mu(-2:imx+2,-2:jmx+2,-2:kmx+2) => mu_t(:,:,:)
          case ('sst', 'sst2003')
            sst_mu(-2:imx+2,-2:jmx+2,-2:kmx+2) => mu_t(:,:,:)
            !-- sst blending funciton F1 --!
            call alloc(sst_F1, -2,imx+2, -2,jmx+2, -2,kmx+2)
            sst_F1=0.
            !-- sst blnding function setup compete--!
          case ('kkl')
            kkl_mu(-2:imx+2,-2:jmx+2,-2:kmx+2) => mu_t(:,:,:)
          case DEFAULT
            !call turbulence_read_error()
            Fatal_error
        end select
      end if
      ! --- end turbulent viscosity setup ---!
    end subroutine setup_viscosity
Call graph
setup_viscosity calls alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_solver calls setup_viscosity
start_run calls setup_solver
main calls start_run