setup_all – FEST-3D
setup_all Subroutine
29 statements
Source File
public subroutine setup_all()
To setup, create, allocate memory, link pointer (everything that is required before first iteration
Arguments
None
Calls
Contents
Source Code
setup_all
Source Code
      subroutine setup_all()
        !< To setup, create, allocate memory, link pointer
        !<    (everything that is required before first iteration
          implicit none
          call dmsg(1, 'create_erase', 'setup_all')
          call get_process_data()           ! parallel calls
          call read_layout_file(process_id) ! reads layout file calls
          call read_input_and_controls()    ! all input config file are read
          call setup_grid(grid_file_buf)    ! read grid
          call setup_geometry()             ! calculate geometric quantities (area, normal and volume)
          call setup_state()                ! allocate memroy and initialize state variable
          call setup_transport()            ! allocate memroy to viscosity
          call setup_gradients()            ! allocate memroy to gradients
          call setup_bc()                   ! set id and face_names array
          call allocate_memory()
          call allocate_buffer_cells(3)     ! parallel buffers (MPI interafce communication)
          call setup_scheme()               ! face convective flux: memory and scheme
          if(turbulence /= 'none') then
            call write_surfnode()
            call setup_wall_dist()
            call find_wall_dist()
          end if
          call setup_sst_F1()
          call link_aliases_solver()
          call setup_resnorm()
          call initmisc()
          checkpoint_iter_count = 0
          call checkpoint()  ! Create an initial dump file
          call setup_time()
          call dmsg(5, 'create_erase', 'setup_all', 'Setup complete')
      end subroutine setup_all
Call graph
setup_all calls setup_scheme, initmisc, link_aliases_solver, setup_sst_f1, setup_geometry, allocate_memory, setup_time, setup_resnorm, setup_gradients, checkpoint, setup_state, allocate_buffer_cells, find_wall_dist, setup_wall_dist, write_surfnode, read_input_and_controls, dmsg, setup_bc, setup_transport, get_process_data, read_layout_file, setup_grid