setup_time – FEST-3D
setup_time Subroutine
15 statements
Source File
public subroutine setup_time(delta_t, control, dims)
Allocate memeroy and setup initial clock
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(:,:,:), allocatable :: delta_t
Local time increment value at each cell center
type(controltype), intent(in) :: control
Control parameters
type(extent), intent(in) :: dims
Extent of the domain:imx,jmx,kmx
Calls
Called by
Contents
Source Code
setup_time
Source Code
        subroutine setup_time(delta_t, control, dims)
          !< Allocate memeroy and setup initial clock
            implicit none
            type(controltype), intent(in) :: control
            !< Control parameters
            type(extent), intent(in) :: dims
            !< Extent of the domain:imx,jmx,kmx
            real(wp), dimension(:,:,:), allocatable, intent(out) :: delta_t
            !< Local time increment value at each cell center
            DebugCall('initmisc')
            imx = dims%imx
            jmx = dims%jmx
            kmx = dims%kmx
            n_var = control%n_var
            call alloc(delta_t, 1, imx-1, 1, jmx-1, 1, kmx-1, &
                    errmsg='Error: Unable to allocate memory for delta_t.')
            CALL SYSTEM_CLOCK(COUNT_RATE=nb_ticks_sec, COUNT_MAX=nb_ticks_max)
            CALL SYSTEM_CLOCK(COUNT=nb_ticks_initial)
            CALL CPU_TIME(t1)
        end subroutine setup_time
Call graph
setup_time calls alloc, debugcall
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_solver calls setup_time
start_run calls setup_solver
main calls start_run