setup_update – FEST-3D
setup_update Subroutine
22 statements
Source File
public subroutine setup_update()
Allocate memory to variables required based on the time-integration scheme.
Arguments
None
Calls
Called by
Contents
Source Code
setup_update
Source Code
      subroutine setup_update()
        !< Allocate memory to variables required based
        !< on the time-integration scheme.
        implicit none
        call alloc(u1,1,n_var)
        call alloc(u2,1,n_var)
        call alloc(R ,1,n_var)
        call alloc(aux,-2,imx+2,-2,jmx+2,-2,kmx+2,1,n_var)
        select case (time_step_accuracy)
          case ("none")
            ! Do nothing
            continue
          case ("RK2", "RK4")
            call alloc(U_store,-2,imx+2,-2,jmx+2,-2,kmx+2,1,n_var)
            call alloc(R_store, 1,imx-1, 1,jmx-1, 1,kmx-1,1,n_var)
          case ("TVDRK2", "TVDRK3", "TVDRK4")
            call alloc(U_store,-2,imx+2,-2,jmx+2,-2,kmx+2,1,n_var)
          case ("implicit")
            call setup_lusgs()
          case ("plusgs")
            call setup_plusgs()
          case default
            Fatal_error
        end select
      end subroutine setup_update
Call graph
setup_update calls alloc, setup_lusgs, setup_plusgs
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_lusgs calls alloc
setup_plusgs calls alloc
setup_solver calls setup_update
start_run calls setup_solver
main calls start_run