setup_state – FEST-3D
setup_state Subroutine
20 statements
Source File
public subroutine setup_state(files, qp, control, scheme, flow, dims)
Setup the state module. This subroutine should be run before the state variables are initilized. This subroutine allocates the memory for state variables and sets up the aliases to refer to the components of the state
Arguments
Type Intent Optional Attributes Name
type(filetype), intent(inout) :: files
Files' name and handler
real(kind=wp), intent(inout), dimension(:,:,:,:), allocatable, target :: qp
Store primitive variable at cell center
type(controltype), intent(inout) :: control
Control parameters
type(schemetype), intent(in) :: scheme
finite-volume Schemes
type(flowtype), intent(inout) :: flow
Information about fluid flow: freestream-speed, ref-viscosity,etc.
type(extent), intent(inout) :: dims
Extent of the domain:imx,jmx,kmx
Calls
Called by
Contents
Source Code
setup_state
Source Code
        subroutine setup_state(files, qp, control, scheme, flow, dims)
            !< Setup the state module.
            !< This subroutine should be run before the state variables
            !< are initilized. This subroutine allocates the memory for
            !< state variables and sets up the aliases to refer to the
            !< components of the state
            !-----------------------------------------------------------
            implicit none
            type(filetype), intent(inout) :: files
            !< Files' name and handler
            type(controltype), intent(inout) :: control
            !< Control parameters
            type(schemetype), intent(in) :: scheme
            !< finite-volume Schemes
            type(flowtype), intent(inout) :: flow
            !< Information about fluid flow: freestream-speed, ref-viscosity,etc.
            type(extent), intent(inout) :: dims
            !< Extent of the domain:imx,jmx,kmx
            real(wp), dimension(:,:,:,:), allocatable, intent(inout), target :: qp
            !< Store primitive variable at cell center
            DebugCall("setup_state")
            n_var = control%n_var
            imx = dims%imx
            jmx = dims%jmx
            kmx = dims%kmx
            call set_n_var_value(control, scheme)
            dims%n_var = control%n_var
            !call allocate_memory(qp)
            call alloc(qp, -2, imx+2, -2, jmx+2, -2, kmx+2, 1, n_var, AErrMsg("qp"))
            allocate(control%previous_res(1:control%n_var+1))
            !call link_aliases(scheme)
            call init_infinity_values(scheme, flow)
            call initstate(files, qp, control, scheme, flow, dims)
        end subroutine setup_state
Call graph
setup_state calls aerrmsg, initstate, alloc, init_infinity_values, debugcall, set_n_var_value
initstate calls debugcall, verify_write_control, init_state_with_infinity_values, read_file
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
init_infinity_values calls debugcall, sound_speed_inf
set_n_var_value calls debugcall
verify_write_control calls lcase
init_state_with_infinity_values calls debugcall
read_file calls verify_read_control, read_file_tec, open_file, read_restart_file, close_file, read_file_vtk, setup_file
verify_read_control calls lcase
open_file calls debugcall
close_file calls debugcall
setup_file calls debugcall
setup_solver calls setup_state
start_run calls setup_solver
main calls start_run