setup_resnorm – FEST-3D
setup_resnorm Subroutine
6 statements
Source File
public subroutine setup_resnorm()
allocate memory, setup scale and file to write
Arguments
None
Calls
Called by
Contents
Source Code
setup_resnorm
Source Code
    subroutine setup_resnorm()
      !< allocate memory, setup scale and file to write
      implicit none
      call allocate_memory()
      call setup_scale()
      call setup_file()
    end subroutine setup_resnorm
Call graph
setup_resnorm calls allocate_memory, setup_scale, setup_file
allocate_memory calls alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
setup_solver calls setup_resnorm
start_run calls setup_solver
main calls start_run