setup_bc – FEST-3D
setup_bc Subroutine
37 statements
Source File
public subroutine setup_bc()
Initialization and allocate memory of boundary condition variables
Arguments
None
Calls
Called by
Contents
Source Code
setup_bc
Source Code
    subroutine setup_bc()
      !< Initialization and allocate memory of boundary condition variables
      implicit none
      !check for periodic bc
      if(PbcId(1)>=0) imin_id=-10
      if(PbcId(2)>=0) imax_id=-10
      if(PbcId(3)>=0) jmin_id=-10
      if(PbcId(4)>=0) jmax_id=-10
      if(PbcId(5)>=0) kmin_id=-10
      if(PbcId(6)>=0) kmax_id=-10
      ! assign name to each face
      face_names(1) = "imin"
      face_names(2) = "imax"
      face_names(3) = "jmin"
      face_names(4) = "jmax"
      face_names(5) = "kmin"
      face_names(6) = "kmax"
      id(1) =  imin_id
      id(2) =  imax_id
      id(3) =  jmin_id
      id(4) =  jmax_id
      id(5) =  kmin_id
      id(6) =  kmax_id
      c2 = 1 + accur
      c3 = 0.5*accur
      c1 = c2-c3
      call read_fixed_values()
      call alloc(make_F_flux_zero, 1,imx)
      call alloc(make_G_flux_zero, 1,jmx)
      call alloc(make_H_flux_zero, 1,kmx)
      make_F_flux_zero=1
      make_G_flux_zero=1
      make_H_flux_zero=1
      if(imin_id==-5 .or. imin_id==-6 .or. imin_id==-7) make_F_flux_zero(1)=0
      if(jmin_id==-5 .or. jmin_id==-6 .or. jmin_id==-7) make_G_flux_zero(1)=0
      if(kmin_id==-5 .or. kmin_id==-6 .or. kmin_id==-7) make_H_flux_zero(1)=0
      if(imax_id==-5 .or. imax_id==-6 .or. imax_id==-7) make_F_flux_zero(imx)=0
      if(jmax_id==-5 .or. jmax_id==-6 .or. jmax_id==-7) make_G_flux_zero(jmx)=0
      if(kmax_id==-5 .or. kmax_id==-6 .or. kmax_id==-7) make_H_flux_zero(kmx)=0
    end subroutine setup_bc
Call graph
setup_bc calls read_fixed_values, alloc
read_fixed_values calls get_fixed_values, fill_fixed_values
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
get_fixed_values calls set_value
fill_fixed_values calls set_value
setup_solver calls setup_bc
setup_all calls setup_bc
start_run calls setup_solver
main calls start_run