setup_surface – FEST-3D
setup_surface Subroutine
17 statements
Source File
private subroutine setup_surface(files, control, bc)
Open MPI_shared write file, allocate memory and setup pointers
Arguments
Type Intent Optional Attributes Name
type(filetype), intent(in) :: files
type(controltype), intent(in) :: control
type(boundarytype), intent(in) :: bc
Calls
Called by
Contents
Source Code
setup_surface
Source Code
    subroutine setup_surface(files, control, bc)
      !< Open MPI_shared write file, allocate memory and
      !< setup pointers
      implicit none
      type(boundarytype), intent(in) :: bc
      type(filetype), intent(in) :: files
      type(controltype), intent(in) :: control
      integer :: stat
      DebugCall('setup_surface')
      if(process_id==0)then
      open(files%NODESURF_FILE_UNIT, file=files%surface_node_points, iostat=stat)
      if(stat==0) close(files%NODESURF_FILE_UNIT, status='delete')
      end if
      call mpi_barrier(MPI_COMM_WORLD,ierr)
      call MPI_FILE_OPEN(MPI_COMM_WORLD, files%surface_node_points, &
                        MPI_MODE_WRONLY + MPI_MODE_CREATE + MPI_MODE_EXCL, &
                        MPI_INFO_NULL, thisfile, ierr)
      call find_wall(bc)
      call allocate_memory(control)
      call link_aliases()
    end subroutine setup_surface
Call graph
setup_surface calls find_wall, link_aliases, allocate_memory, mpi_file_open, mpi_barrier, debugcall
link_aliases calls debugcall
allocate_memory calls debugcall, alloc
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
write_surfnode calls setup_surface
setup_solver calls write_surfnode
start_run calls setup_solver
main calls start_run