sound_speed_inf – FEST-3D
sound_speed_inf Function
5 statements
Source File
private function sound_speed_inf() result(a)
Return the free stream speed of sound.
Arguments
None
Return Value real
Called by
Contents
Source Code
sound_speed_inf
Source Code
        function sound_speed_inf() result(a)
            !< Return the free stream speed of sound.
            !-----------------------------------------------------------
            implicit none
            real :: a
            a = sqrt(gm * pressure_inf / density_inf)
        end function sound_speed_inf
Call graph
init_infinity_values calls sound_speed_inf
setup_state calls init_infinity_values
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run