SpectralRadius – FEST-3D
SpectralRadius Function
37 statements
Source File
public function SpectralRadius(ql, qr, inputs, c1, c2)
Calculate the spectral radius
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(1:n_var) :: ql
real, intent(in), dimension(1:n_var) :: qr
real, intent(in), dimension(1:7) :: inputs
real, intent(in), dimension(1:3) :: c1
real, intent(in), dimension(1:3) :: c2
Return Value real
Called by
Contents
Source Code
SpectralRadius
Source Code
    function SpectralRadius(ql, qr, inputs, c1, c2)
      !< Calculate the spectral radius
      implicit none
      real, dimension(1:n_var), intent(in) :: ql
      real, dimension(1:n_var), intent(in) :: qr
      real, dimension(1:7)    , intent(in) :: inputs
      real, dimension(1:3)    , intent(in) :: c1
      real, dimension(1:3)    , intent(in) :: c2
      ! local variables
      real                                 :: SpectralRadius
      real                                 :: NormalSpeed
      real                                 :: SpeedOfSound
      real                                 :: vis
      real                                 :: mu
      real                                 :: rho
      real                                 :: distance
      !extract inputs
      real :: Area
      real :: nx
      real :: ny
      real :: nz
      real :: volume
      real :: mm
      real :: tm
      Area = inputs(1)
      nx   = inputs(2)
      ny   = inputs(3)
      nz   = inputs(4)
      volume = inputs(5)
      mm   = inputs(6)
      tm   = inputs(7)
      ! in state vector q (2-4) are the cell center velocity
      NormalSpeed = 0.5 * ( ( ( ql(2) + qr(2) ) * nx ) &
                          + ( ( ql(3) + qr(3) ) * ny ) &
                          + ( ( ql(4) + qr(4) ) * nz ) &
                          )
      NormalSpeed = abs(NormalSpeed)
      SpeedOfSound = 0.5*( sqrt(gm*ql(5)/ql(1)) + sqrt(gm*qr(5)/qr(1)) )
      ! visocus part
      mu  = mm/Pr + tm/tPr
      rho = 0.5*( ql(1) + qr(1) )
      distance = sqrt((c1(1)-c2(1))**2 + (c1(2)-c2(2))**2 +(c1(3)-c2(3))**2)
      vis = gm * (mm/pr + tm/tpr) / ( rho * distance )
      SpectralRadius = ( NormalSpeed + SpeedOfSound + vis) * Area
    end function SpectralRadius
Call graph
update_sa_variables calls spectralradius
update_kkl_variables calls spectralradius
update_sst_variables calls spectralradius
update_lctm2015 calls spectralradius
update_laminar_variables calls spectralradius
update_with_lusgs calls update_sa_variables, update_kkl_variables, update_sst_variables, update_lctm2015, update_laminar_variables
get_next_solution calls update_with_lusgs
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step