start_run – FEST-3D
start_run Subroutine
6 statements
Source File
public subroutine start_run()
Starting the solver setup
Arguments
None
Calls
Called by
Contents
Source Code
start_run
Source Code
        subroutine start_run()
          !< Starting the solver setup
          implicit none
          integer :: ierr
          call MPI_INIT(ierr)
          call setup_solver()
        end subroutine start_run
Call graph
start_run calls setup_solver, mpi_init
setup_solver calls initmisc, mpi_barrier, setup_geometry, setup_time, setup_gradients, checkpoint, setupcc, setup_state, setup_scheme, find_wall_dist, setup_wall_dist, debugcall, write_surfnode, read_input_and_controls, setup_interface, setup_bc, setup_resnorm, setup_viscosity, get_process_data, setup_update, read_layout_file, setup_grid
main calls start_run