subsonic_inlet – FEST-3D
subsonic_inlet Subroutine
34 statements
Source File
private subroutine subsonic_inlet(face)
Subsonic inlet boundary condition. All the state variables's value expect pressure is fixed and pressure is copied from inside the domain
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: face
Name of the face at which boundary condition is called
Calls
Called by
Contents
Source Code
subsonic_inlet
Source Code
      subroutine subsonic_inlet(face)
        !< Subsonic inlet boundary condition.
        !< All the state variables's value expect pressure
        !< is fixed and pressure is copied from inside the
        !< domain
        implicit none
        character(len=*), intent(in) :: face
        !< Name of the face at which boundary condition is called
        if(current_iter<=2)then
        call fix(density , fixed_density , face)
        call fix(x_speed , fixed_x_speed , face)
        call fix(y_speed , fixed_y_speed , face)
        call fix(z_speed , fixed_z_speed , face)
        select case (turbulence)
          case('none')
            !do nothing
            continue
          case('sa', 'saBC')
            call fix(tv, fixed_tv, face)
          case('sst', 'sst2003')
            call check_if_value_fixed("sst")
            call fix(tk, fixed_tk, face)
            call fix(tw, fixed_tw, face)
          case('kkl')
            call check_if_value_fixed("kkl")
            call fix(tk, fixed_tk, face)
            call fix(tkl, fixed_tw, face)
          case DEFAULT
           ! call turbulence_read_error()
           Fatal_error
        end select
        select case(trim(transition))
          case('lctm2015')
            call check_if_value_fixed("lctm2015")
            call fix(tgm, fixed_tgm, face)
          case DEFAULT
            continue
        end select
        end if
        call copy3(pressure, "flat", face)
      end subroutine subsonic_inlet
Call graph
subsonic_inlet calls check_if_value_fixed, copy3, fix
populate_ghost_primitive calls subsonic_inlet
get_total_conservative_residue calls populate_ghost_primitive
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step