total_pressure – FEST-3D
total_pressure Subroutine
498 statements
Source File
private subroutine total_pressure(face)
Total Pressure Riemann boundary condition
Arguments
Type Intent Optional Attributes Name
character(len=*) :: face
Calls
Called by
Contents
Source Code
total_pressure
Source Code
    subroutine total_pressure(face)
      !< Total Pressure Riemann boundary condition
      implicit none
      character(len=*) :: face
      real :: cinf, cexp   ! speed of sound
      real :: Rinf, Rexp   ! Riemann invarient
      real :: Uninf, Unexp ! face normal speed
      real :: Unb ! normal velocity boundary
      real :: Cb  ! speed of sound boundary
      real :: vel_diff
      real :: u,v,w
      real :: uf, vf, wf
      real :: Mb
      integer :: i,j,k
      select case(face)
        case("imin")
          do k = 1,kmx-1
            do j = 1,jmx-1
              do i = 1,1
                ! interior cell
                u = x_speed(i,j,k)
                v = y_speed(i,j,k)
                w = z_speed(i,j,k)
                ! ghost cell
                uf = x_speed_inf!x_speed(i-1,j,k)
                vf = y_speed_inf!y_speed(i-1,j,k)
                wf = z_speed_inf!z_speed(i-1,j,k)
                cexp = sqrt(gm*pressure(i,j,k)/density(i,j,k))
                !cinf = sqrt(gm*pressure(i-1,j,k)/density(i-1,j,k))
                cinf = sqrt(gm*pressure_inf/density_inf)
                Unexp = u *(-xnx(i,j,k)) + v *(-xny(i,j,k)) + w *(-xnz(i,j,k))
                Uninf = uf*(-xnx(i,j,k)) + vf*(-xny(i,j,k)) + wf*(-xnz(i,j,k))
                Rinf  = Uninf - 2*cinf/(gm-1.)
                Rexp  = Unexp + 2*cexp/(gm-1.)
                Unb   = 0.5*(Rexp + Rinf)
                Cb    = 0.25*(gm-1.)*(Rexp - Rinf)
                if(Unb > 0.)then
                  vel_diff = Unb - Unexp
                  x_speed(i-1,j,k) = x_speed(i,j,k) + vel_diff*(-xnx(i,j,k))
                  y_speed(i-1,j,k) = y_speed(i,j,k) + vel_diff*(-xny(i,j,k))
                  z_speed(i-1,j,k) = z_speed(i,j,k) + vel_diff*(-xnz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call copy3(tv, "flat", face)
                    case('sst', 'sst2003')
                      call copy3(tk, "flat", face)
                      call copy3(tw, "flat", face)
                    case('kkl')
                      call copy3(tk, "flat", face)
                      call copy3(tkl, "flat", face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call copy3(tgm, "flat", face)
                    case DEFAULT
                      continue
                  end select
                else
                  vel_diff = Unb - Uninf
                  x_speed(i-1,j,k) = x_speed_inf + vel_diff*(-xnx(i,j,k))
                  y_speed(i-1,j,k) = y_speed_inf + vel_diff*(-xny(i,j,k))
                  z_speed(i-1,j,k) = z_speed_inf + vel_diff*(-xnz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call fix(tv, fixed_tv, face)
                    case('sst', 'sst2003')
                      call check_if_value_fixed("sst")
                      call fix(tk, fixed_tk, face)
                      call fix(tw, fixed_tw, face)
                    case('kkl')
                      call check_if_value_fixed("kkl")
                      call fix(tk, fixed_tk, face)
                      call fix(tkl, fixed_tkl, face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call check_if_value_fixed("lctm2015")
                      call fix(tgm, fixed_tgm, face)
                    case DEFAULT
                      continue
                  end select
                end if
                Mb = sqrt(x_speed(i-1,j,k)**2+y_speed(i-1,j,k)**2+z_speed(i-1,j,k)**2)/Cb
                pressure(i-1,j,k) = fixed_Tpressure(1)/(((1+0.5*(gm-1.)*Mb*Mb))**(gm/(gm-1.)))
                density(i-1,j,k) = gm*pressure(i-1,j,k)/(Cb*Cb)
              end do
            end do
          end do
          qp(-1,:,:,:) = qp(0,:,:,:)
          qp(-2,:,:,:) = qp(0,:,:,:)
         case("imax")
          do k = 1,kmx-1
            do j = 1,jmx-1
              do i = imx,imx
                ! interior cell
                u = x_speed(i-1,j,k)
                v = y_speed(i-1,j,k)
                w = z_speed(i-1,j,k)
                ! ghost cell
                uf = x_speed_inf!x_speed(i,j,k)
                vf = y_speed_inf!y_speed(i,j,k)
                wf = z_speed_inf!z_speed(i,j,k)
                cexp = sqrt(gm*pressure(i-1,j,k)/density(i-1,j,k))
                !cinf = sqrt(gm*pressure(i,j,k)/density(i,j,k))
                cinf = sqrt(gm*pressure_inf/density_inf)
                Unexp = u *(xnx(i,j,k)) + v *(xny(i,j,k)) + w *(xnz(i,j,k))
                Uninf = uf*(xnx(i,j,k)) + vf*(xny(i,j,k)) + wf*(xnz(i,j,k))
                Rinf  = Uninf - 2*cinf/(gm-1.)
                Rexp  = Unexp + 2*cexp/(gm-1.)
                Unb   = 0.5*(Rexp + Rinf)
                Cb    = 0.25*(gm-1.)*(Rexp - Rinf)
                if(Unb > 0.)then
                  vel_diff = Unb - Unexp
                  x_speed(i,j,k) = x_speed(i-1,j,k) + vel_diff*(xnx(i,j,k))
                  y_speed(i,j,k) = y_speed(i-1,j,k) + vel_diff*(xny(i,j,k))
                  z_speed(i,j,k) = z_speed(i-1,j,k) + vel_diff*(xnz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call copy3(tv, "flat", face)
                    case('sst', 'sst2003')
                      call copy3(tk, "flat", face)
                      call copy3(tw, "flat", face)
                    case('kkl')
                      call copy3(tk, "flat", face)
                      call copy3(tkl, "flat", face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call copy3(tgm, "flat", face)
                    case DEFAULT
                      continue
                  end select
                else
                  vel_diff = Unb - Uninf
                  x_speed(i,j,k) = x_speed_inf + vel_diff*(xnx(i,j,k))
                  y_speed(i,j,k) = y_speed_inf + vel_diff*(xny(i,j,k))
                  z_speed(i,j,k) = z_speed_inf + vel_diff*(xnz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call fix(tv, fixed_tv, face)
                    case('sst', 'sst2003')
                      call check_if_value_fixed("sst")
                      call fix(tk, fixed_tk, face)
                      call fix(tw, fixed_tw, face)
                    case('kkl')
                      call check_if_value_fixed("kkl")
                      call fix(tk, fixed_tk, face)
                      call fix(tkl, fixed_tkl, face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call check_if_value_fixed("lctm2015")
                      call fix(tgm, fixed_tgm, face)
                    case DEFAULT
                      continue
                  end select
                end if
                Mb = sqrt(x_speed(i,j,k)**2+y_speed(i,j,k)**2+z_speed(i,j,k)**2)/Cb
                pressure(i,j,k) = fixed_Tpressure(2)/(((1+0.5*(gm-1.)*Mb*Mb))**(gm/(gm-1.)))
                density(i,j,k) = gm*pressure(i,j,k)/(Cb*Cb)
              end do
            end do
          end do
          qp(imx+1,:,:,:) = qp(imx,:,:,:)
          qp(imx+2,:,:,:) = qp(imx,:,:,:)
        case("jmin")
          do k = 1,kmx-1
            do j = 1,1
              do i = 1,imx-1
                ! interior cell
                u = x_speed(i,j,k)
                v = y_speed(i,j,k)
                w = z_speed(i,j,k)
                ! ghost cell
                uf = x_speed_inf!x_speed(i,j-1,k)
                vf = y_speed_inf!y_speed(i,j-1,k)
                wf = z_speed_inf!z_speed(i,j-1,k)
                cexp = sqrt(gm*pressure(i,j,k)/density(i,j,k))
                !cinf = sqrt(gm*pressure(i,j-1,k)/density(i,j-1,k))
                cinf = sqrt(gm*pressure_inf/density_inf)
                Unexp = u *(-ynx(i,j,k)) + v *(-yny(i,j,k)) + w *(-ynz(i,j,k))
                Uninf = uf*(-ynx(i,j,k)) + vf*(-yny(i,j,k)) + wf*(-ynz(i,j,k))
                Rinf  = Uninf - 2*cinf/(gm-1.)
                Rexp  = Unexp + 2*cexp/(gm-1.)
                Unb   = 0.5*(Rexp + Rinf)
                Cb    = 0.25*(gm-1.)*(Rexp - Rinf)
                if(Unb > 0.)then
                  vel_diff = Unb - Unexp
                  x_speed(i,j-1,k) = x_speed(i,j,k) + vel_diff*(-ynx(i,j,k))
                  y_speed(i,j-1,k) = y_speed(i,j,k) + vel_diff*(-yny(i,j,k))
                  z_speed(i,j-1,k) = z_speed(i,j,k) + vel_diff*(-ynz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call copy3(tv, "flat", face)
                    case('sst', 'sst2003')
                      call copy3(tk, "flat", face)
                      call copy3(tw, "flat", face)
                    case('kkl')
                      call copy3(tk, "flat", face)
                      call copy3(tkl, "flat", face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call copy3(tgm, "flat", face)
                    case DEFAULT
                      continue
                  end select
                else
                  vel_diff = Unb - Uninf
                  x_speed(i,j-1,k) = x_speed_inf + vel_diff*(-ynx(i,j,k))
                  y_speed(i,j-1,k) = y_speed_inf + vel_diff*(-yny(i,j,k))
                  z_speed(i,j-1,k) = z_speed_inf + vel_diff*(-ynz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call fix(tv, fixed_tv, face)
                    case('sst', 'sst2003')
                      call check_if_value_fixed("sst")
                      call fix(tk, fixed_tk, face)
                      call fix(tw, fixed_tw, face)
                    case('kkl')
                      call check_if_value_fixed("kkl")
                      call fix(tk, fixed_tk, face)
                      call fix(tkl, fixed_tkl, face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call check_if_value_fixed("lctm2015")
                      call fix(tgm, fixed_tgm, face)
                    case DEFAULT
                      continue
                  end select
                end if
                Mb = sqrt(x_speed(i,j-1,k)**2+y_speed(i,j-1,k)**2+z_speed(i,j-1,k)**2)/Cb
                pressure(i,j-1,k) = fixed_Tpressure(3)/(((1+0.5*(gm-1.)*Mb*Mb))**(gm/(gm-1.)))
                density(i,j-1,k) = gm*pressure(i,j-1,k)/(Cb*Cb)
              end do
            end do
          end do
          qp(:,-1,:,:) = qp(:,0,:,:)
          qp(:,-2,:,:) = qp(:,0,:,:)
        case("jmax")
          do k = 1,kmx-1
            do j = jmx,jmx
              do i = 1,imx-1
                ! interior cell
                u = x_speed(i,j-1,k)
                v = y_speed(i,j-1,k)
                w = z_speed(i,j-1,k)
                ! ghost cell
                uf = x_speed_inf!x_speed(i,j,k)
                vf = y_speed_inf!y_speed(i,j,k)
                wf = z_speed_inf!z_speed(i,j,k)
                cexp = sqrt(gm*pressure(i,j-1,k)/density(i,j-1,k))
                !cinf = sqrt(gm*pressure(i,j,k)/density(i,j,k))
                cinf = sqrt(gm*pressure_inf/density_inf)
                Unexp = u *(ynx(i,j,k)) + v *(yny(i,j,k)) + w *(ynz(i,j,k))
                Uninf = uf*(ynx(i,j,k)) + vf*(yny(i,j,k)) + wf*(ynz(i,j,k))
                Rinf  = Uninf - 2*cinf/(gm-1.)
                Rexp  = Unexp + 2*cexp/(gm-1.)
                Unb   = 0.5*(Rexp + Rinf)
                Cb    = 0.25*(gm-1.)*(Rexp - Rinf)
                if(Unb > 0.)then
                  vel_diff = Unb - Unexp
                  x_speed(i,j,k) = x_speed(i,j-1,k) + vel_diff*(ynx(i,j,k))
                  y_speed(i,j,k) = y_speed(i,j-1,k) + vel_diff*(yny(i,j,k))
                  z_speed(i,j,k) = z_speed(i,j-1,k) + vel_diff*(ynz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call copy3(tv, "flat", face)
                    case('sst', 'sst2003')
                      call copy3(tk, "flat", face)
                      call copy3(tw, "flat", face)
                    case('kkl')
                      call copy3(tk, "flat", face)
                      call copy3(tkl, "flat", face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call copy3(tgm, "flat", face)
                    case DEFAULT
                      continue
                  end select
                else
                  vel_diff = Unb - Uninf
                  x_speed(i,j,k) = x_speed_inf + vel_diff*(ynx(i,j,k))
                  y_speed(i,j,k) = y_speed_inf + vel_diff*(yny(i,j,k))
                  z_speed(i,j,k) = z_speed_inf + vel_diff*(ynz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call fix(tv, fixed_tv, face)
                    case('sst', 'sst2003')
                      call check_if_value_fixed("sst")
                      call fix(tk, fixed_tk, face)
                      call fix(tw, fixed_tw, face)
                    case('kkl')
                      call check_if_value_fixed("kkl")
                      call fix(tk, fixed_tk, face)
                      call fix(tkl, fixed_tkl, face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call check_if_value_fixed("lctm2015")
                      call fix(tgm, fixed_tgm, face)
                    case DEFAULT
                      continue
                  end select
                end if
                Mb = sqrt(x_speed(i,j,k)**2+y_speed(i,j,k)**2+z_speed(i,j,k)**2)/Cb
                pressure(i,j,k) = fixed_Tpressure(4)/(((1+0.5*(gm-1.)*Mb*Mb))**(gm/(gm-1.)))
                density(i,j,k) = gm*pressure(i,j,k)/(Cb*Cb)
              end do
            end do
          end do
          qp(:,jmx+1,:,:) = qp(:,jmx,:,:)
          qp(:,jmx+2,:,:) = qp(:,jmx,:,:)
        case("kmin")
          do k = 1,1
            do j = 1,jmx-1
              do i = 1,imx-1
                ! interior cell
                u = x_speed(i,j,k)
                v = y_speed(i,j,k)
                w = z_speed(i,j,k)
                ! ghost cell
                uf = x_speed_inf!x_speed(i,j,k-1)
                vf = y_speed_inf!y_speed(i,j,k-1)
                wf = z_speed_inf!z_speed(i,j,k-1)
                cexp = sqrt(gm*pressure(i,j,k)/density(i,j,k))
                !cinf = sqrt(gm*pressure(i,j,k-1)/density(i,j,k-1))
                cinf = sqrt(gm*pressure_inf/density_inf)
                Unexp = u *(-znx(i,j,k)) + v *(-zny(i,j,k)) + w *(-znz(i,j,k))
                Uninf = uf*(-znx(i,j,k)) + vf*(-zny(i,j,k)) + wf*(-znz(i,j,k))
                Rinf  = Uninf - 2*cinf/(gm-1.)
                Rexp  = Unexp + 2*cexp/(gm-1.)
                Unb   = 0.5*(Rexp + Rinf)
                Cb    = 0.25*(gm-1.)*(Rexp - Rinf)
                if(Unb > 0.)then
                  vel_diff = Unb - Unexp
                  x_speed(i,j,k-1) = x_speed(i,j,k) + vel_diff*(-znx(i,j,k))
                  y_speed(i,j,k-1) = y_speed(i,j,k) + vel_diff*(-zny(i,j,k))
                  z_speed(i,j,k-1) = z_speed(i,j,k) + vel_diff*(-znz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call copy3(tv, "flat", face)
                    case('sst', 'sst2003')
                      call copy3(tk, "flat", face)
                      call copy3(tw, "flat", face)
                    case('kkl')
                      call copy3(tk, "flat", face)
                      call copy3(tkl, "flat", face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call copy3(tgm, "flat", face)
                    case DEFAULT
                      continue
                  end select
                else
                  vel_diff = Unb - Uninf
                  x_speed(i,j,k-1) = x_speed_inf + vel_diff*(-znx(i,j,k))
                  y_speed(i,j,k-1) = y_speed_inf + vel_diff*(-zny(i,j,k))
                  z_speed(i,j,k-1) = z_speed_inf + vel_diff*(-znz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call fix(tv, fixed_tv, face)
                    case('sst', 'sst2003')
                      call check_if_value_fixed("sst")
                      call fix(tk, fixed_tk, face)
                      call fix(tw, fixed_tw, face)
                    case('kkl')
                      call check_if_value_fixed("kkl")
                      call fix(tk, fixed_tk, face)
                      call fix(tkl, fixed_tkl, face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call check_if_value_fixed("lctm2015")
                      call fix(tgm, fixed_tgm, face)
                    case DEFAULT
                      continue
                  end select
                end if
                Mb = sqrt(x_speed(i,j,k)**2+y_speed(i,j,k)**2+z_speed(i,j,k)**2)/Cb
                pressure(i,j,k-1) = fixed_Tpressure(5)/(((1+0.5*(gm-1.)*Mb*Mb))**(gm/(gm-1.)))
                density(i,j,k-1) = gm*pressure(i,j,k-1)/(Cb*Cb)
              end do
            end do
          end do
          qp(:,:,-1,:) = qp(:,:,0,:)
          qp(:,:,-2,:) = qp(:,:,0,:)
        case("kmax")
          do k = kmx,kmx
            do j = 1,jmx-1
              do i = 1,imx-1
                ! interior cell
                u = x_speed(i,j,k-1)
                v = y_speed(i,j,k-1)
                w = z_speed(i,j,k-1)
                ! ghost cell
                uf = x_speed_inf!x_speed(i,j,k)
                vf = y_speed_inf!y_speed(i,j,k)
                wf = z_speed_inf!z_speed(i,j,k)
                cexp = sqrt(gm*pressure(i,j,k-1)/density(i,j,k-1))
                !cinf = sqrt(gm*pressure(i,j,k)/density(i,j,k))
                cinf = sqrt(gm*pressure_inf/density_inf)
                Unexp = u *(znx(i,j,k)) + v *(zny(i,j,k)) + w *(znz(i,j,k))
                Uninf = uf*(znx(i,j,k)) + vf*(zny(i,j,k)) + wf*(znz(i,j,k))
                Rinf  = Uninf - 2*cinf/(gm-1.)
                Rexp  = Unexp + 2*cexp/(gm-1.)
                Unb   = 0.5*(Rexp + Rinf)
                Cb    = 0.25*(gm-1.)*(Rexp - Rinf)
                if(Unb > 0.)then
                  vel_diff = Unb - Unexp
                  x_speed(i,j,k) = x_speed(i,j,k-1) + vel_diff*(znx(i,j,k))
                  y_speed(i,j,k) = y_speed(i,j,k-1) + vel_diff*(zny(i,j,k))
                  z_speed(i,j,k) = z_speed(i,j,k-1) + vel_diff*(znz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call copy3(tv, "flat", face)
                    case('sst', 'sst2003')
                      call copy3(tk, "flat", face)
                      call copy3(tw, "flat", face)
                    case('kkl')
                      call copy3(tk, "flat", face)
                      call copy3(tkl, "flat", face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call copy3(tgm, "flat", face)
                    case DEFAULT
                      continue
                  end select
                else
                  vel_diff = Unb - Uninf
                  x_speed(i,j,k) = x_speed_inf + vel_diff*(znx(i,j,k))
                  y_speed(i,j,k) = y_speed_inf + vel_diff*(zny(i,j,k))
                  z_speed(i,j,k) = z_speed_inf + vel_diff*(znz(i,j,k))
                  select case (turbulence)
                    case('none')
                      !do nothing
                      continue
                    case('sa', 'saBC')
                      call fix(tv, fixed_tv, face)
                    case('sst', 'sst2003')
                      call check_if_value_fixed("sst")
                      call fix(tk, fixed_tk, face)
                      call fix(tw, fixed_tw, face)
                    case('kkl')
                      call check_if_value_fixed("kkl")
                      call fix(tk, fixed_tk, face)
                      call fix(tkl, fixed_tkl, face)
                    case DEFAULT
                      !call turbulence_read_error()
                      Fatal_error
                  end select
                  select case(trim(transition))
                    case('lctm2015')
                      call check_if_value_fixed("lctm2015")
                      call fix(tgm, fixed_tgm, face)
                    case DEFAULT
                      continue
                  end select
                end if
                Mb = sqrt(x_speed(i,j,k)**2+y_speed(i,j,k)**2+z_speed(i,j,k)**2)/Cb
                pressure(i,j,k) = fixed_Tpressure(6)/(((1+0.5*(gm-1.)*Mb*Mb))**(gm/(gm-1.)))
                density(i,j,k) = gm*pressure(i,j,k)/(Cb*Cb)
              end do
            end do
          end do
          qp(:,:,kmx+1,:) = qp(:,:,kmx,:)
          qp(:,:,kmx+2,:) = qp(:,:,kmx,:)
        case DEFAULT
          !print*, "ERROR: wrong face for boundary condition"
          Fatal_error
      end select
    end subroutine total_pressure
Call graph
total_pressure calls check_if_value_fixed, copy3, fix
populate_ghost_primitive calls total_pressure
get_total_conservative_residue calls populate_ghost_primitive
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step