unlink_aliases – FEST-3D
unlink_aliases Subroutine
49 statements
Source File
private subroutine unlink_aliases()
Nullify the pointer link
Arguments
None
Calls
Called by
Contents
Source Code
unlink_aliases
Source Code
        subroutine unlink_aliases()
          !< Nullify the pointer link
            implicit none
            DebugCall("unlink_aliases")
            nullify(density)
            nullify(x_speed)
            nullify(y_speed)
            nullify(z_speed)
            nullify(pressure)
            nullify(density_inf)
            nullify(x_speed_inf)
            nullify(y_speed_inf)
            nullify(z_speed_inf)
            nullify(pressure_inf)
            select case (trim(turbulence))
                case ("none")
                    continue
                  case ("sst", "sst2003", "bsl", "kw", "des-sst")
                    nullify(tk)
                    nullify(tw)
                    nullify(tk_inf)
                    nullify(tw_inf)
                case ("kkl")
                    nullify(tk)
                    nullify(tkl)
                    nullify(tk_inf)
                    nullify(tkl_inf)
                case ("sa", "saBC")
                    nullify(tv)
                    nullify(tv_inf)
                case ("ke")
                    nullify(tk)
                    nullify(te)
                    nullify(tk_inf)
                    nullify(te_inf)
                case ("les")
                    continue
                    ! todo
                case DEFAULT
                  Fatal_error
            end select
            !Transition modeling
            select case(trim(transition))
              case('lctm2015')
                nullify(tgm)
                nullify(tgm_inf)
              case('bc', 'none')
                !do nothing
                continue
              case DEFAULT
                Fatal_error
            end Select
        end subroutine unlink_aliases
Call graph
unlink_aliases calls debugcall
destroy_state calls unlink_aliases
destroy_all calls destroy_state
destroy_solver calls destroy_state
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run