update_with_lusgs – FEST-3D
update_with_lusgs Subroutine
22 statements
Source File
public subroutine update_with_lusgs()
Time-integrate with LU_SGS method
Arguments
None
Calls
Called by
Contents
Source Code
update_with_lusgs
Source Code
    subroutine update_with_lusgs()
      !< Time-integrate with LU_SGS method
      implicit none
      select case(trim(turbulence))
        case('none')
          call update_laminar_variables()
        case('sst', 'sst2003')
          select case(trim(transition))
            case('none', 'bc')
              call update_SST_variables()
            case('lctm2015')
              call update_lctm2015()
            case DEFAULT
              Fatal_error
          end select
        case('kkl')
          call update_KKL_variables()
        case('sa', 'saBC')
          call update_SA_variables()
        case Default
          Fatal_error
      end select
    end subroutine update_with_lusgs
Call graph
update_with_lusgs calls update_sa_variables, update_kkl_variables, update_sst_variables, update_lctm2015, update_laminar_variables
update_sa_variables calls spectralradius, saflux
update_kkl_variables calls spectralradius, kklflux
update_sst_variables calls spectralradius, sstflux
update_lctm2015 calls spectralradius, lctm2015flux
update_laminar_variables calls spectralradius
get_next_solution calls update_with_lusgs
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step