verify_read_control – FEST-3D
verify_read_control Subroutine
165 statements
Source File
public subroutine verify_read_control()
Verify all the variable being asked to read in the output file. This is a fail-safe subroutine which do not allow to read the incorrect input variable Based on previous flow type some varible might be skipped.
Arguments
None
Calls
Called by
Contents
Source Code
verify_read_control
Source Code
    subroutine verify_read_control()
      !< Verify all the variable being asked to read in the output file.
      !< This is a fail-safe subroutine which do not allow to read the incorrect input variable
      !< Based on previous flow type some varible might be skipped.
      implicit none
      integer :: n
      character(len=*), parameter :: err="Control Error: can't read variable - "
      do n = 1,r_count
        select case (trim(lcase(r_list(n))))
          case('velocity','vel','speed','u','v')
            r_list(n) = "Velocity"
          case('density','rho')
            r_list(n) = "Density"
          case('pressure','presssure','p')
            r_list(n) = "Pressure"
          case('mu','viscosity','mu_l','laminar_viscosity','muv','mu_v')
            r_list(n) = "do not read"
           ! if (mu_ref/=0.0) then
           !   r_list(n) = "Mu"
           ! else
           !   print*, err//trim(r_list(n))//" from file"
           !   r_list(n) = "do not read"
           ! end if
          case('mu_t','turbulent_viscosity','mut')
            r_list(n) = "do not read"
            !if (turbulence/='none') then
            !  r_list(n) = "Mu_t"
            !else
            !  print*, err//trim(r_list(n))//" from file"
            !  r_list(n) = "do not read"
            !end if
          case('tke','tk','turbulent_kinetic_enrgy','k')
            select case (trim(turbulence))
              case('sst','sst2003','kw','bsl','kkl','ke','des-sst')
                select case (trim(previous_flow_type))
                  case('sst','sst2003','kw','bsl','kkl','ke','des-sst')
                    r_list(n) = "TKE"
                end select
              case DEFAULT
                print*, err//trim(w_list(n))//" from file"
                r_list(n) = "do not read"
            end select
          case('omega','tw')
            select case (trim(turbulence))
              case('sst','sst2003','kw','bsl','des-sst')
                select case (trim(previous_flow_type))
                  case('sst','sst2003','kw','bsl','des-sst')
                    r_list(n) = "Omega"
                  case DEFAULT
                    print*, err//trim(w_list(n))//" from file"
                    r_list(n) = "do not read"
                end select
              case DEFAULT
                print*, err//trim(w_list(n))//" from file"
                r_list(n) = "do not read"
            end select
          case('dissipation','te','teps','eps')
            select case (trim(turbulence))
              case('ke')
                select case (trim(previous_flow_type))
                  case('ke')
                    r_list(n) = "Dissipation"
                  case DEFAULT
                    print*, err//trim(w_list(n))//" to file"
                    r_list(n) = "do not write"
                end select
              case DEFAULT
                print*, err//trim(w_list(n))//" from file"
                r_list(n) = "do not read"
            end select
          case('kl')
            select case (trim(turbulence))
              case('kkl')
                select case (trim(previous_flow_type))
                  case('kkl')
                    r_list(n) = "Kl"
                  case DEFAULT
                    print*, err//trim(w_list(n))//" to file"
                    r_list(n) = "do not write"
                end select
              case DEFAULT
                print*, err//trim(w_list(n))//" from file"
                r_list(n) = "do not read"
            end select
          case('tv')
            select case (trim(turbulence))
              case('sa', 'saBC')
                select case (trim(previous_flow_type))
                  case('sa', 'saBC')
                    r_list(n) = "tv"
                  case DEFAULT
                    print*, err//trim(w_list(n))//" to file"
                    r_list(n) = "do not write"
                end select
              case DEFAULT
                print*, err//trim(w_list(n))//" from file"
                r_list(n) = "do not read"
            end select
          case('wall_distance', 'dist', 'wall_dist', 'wdist')
            r_list(n) = "do not read"
            !if(turbulence/="none") then
            !  r_list(n) = "Wall_distance"
            !else
            !  print*, err//trim(r_list(n))//" from file"
            !  r_list(n) = "do not read"
            !end if
          case('intermittency')
            select case (trim(turbulence))
              case('saBC')
                select case(trim(previous_flow_type))
                  case('saBC')
                    r_list(n) = "Intermittency"
                  case DEFAULT
                    print*, err//trim(r_list(n))//" to file"
                    r_list(n) = "do not read"
                end select
              case DEFAULT
                print*, err//trim(r_list(n))//" to file"
                r_list(n) = "do not read"
             end select
          case('tgm')
            select case (trim(transition))
              case('lctm2015')
                select case(trim(previous_flow_type))
                  case('sst','sst2003')
                    r_list(n) = "tgm"
                  case DEFAULT
                    print*, err//trim(r_list(n))//" to file"
                    r_list(n) = "do not read"
                end select
              case DEFAULT
                print*, err//trim(r_list(n))//" to file"
                r_list(n) = "do not read"
             end select
          case('resnorm')
            r_list(n) = "do not read"
            !r_list(n) = "Resnorm"
          case('tke_residue')
            r_list(n) = "do not read"
            !r_list(n) = "TKE_residue"
          case('omega_residue')
            r_list(n) = "do not read"
            !w_list(n) = "Omega_residue"
          case('f1')
            r_list(n) = "do not read"
            !r_list(n) = "F1"
          case('dudx')
            r_list(n) = "do not read"
            !r_list(n) = "Dudx"
          case('dudy')
            r_list(n) = "do not read"
            !r_list(n) = "Dudy"
          case('dudz')
            r_list(n) = "do not read"
            !r_list(n) = "Dudz"
          case('dvdx')
            r_list(n) = "do not read"
            !r_list(n) = "Dvdx"
          case('dvdy')
            r_list(n) = "do not read"
            !r_list(n) = "Dvdy"
          case('dvdz')
            r_list(n) = "do not read"
            !r_list(n) = "Dvdz"
          case('dwdx')
            r_list(n) = "do not read"
            !r_list(n) = "Dwdx"
          case('dwdy')
            r_list(n) = "do not read"
            !r_list(n) = "Dwdy"
          case('dwdz')
            r_list(n) = "do not read"
            !r_list(n) = "Dwdz"
          case('dTdx')
            r_list(n) = "do not read"
            !r_list(n) = "DTdx"
          case('dTdy')
            r_list(n) = "do not read"
            !r_list(n) = "DTdy"
          case('dTdz')
            r_list(n) = "do not read"
            !r_list(n) = "DTdz"
          case('dtkdx')
            r_list(n) = "do not read"
            !r_list(n) = "Dtkdx"
          case('dtkdy')
            r_list(n) = "do not read"
            !r_list(n) = "Dtkdy"
          case('dtkdz')
            r_list(n) = "do not read"
            !r_list(n) = "Dtkdz"
          case('dtwdx')
            r_list(n) = "do not read"
            !r_list(n) = "Dtwdx"
          case('dtwdy')
            r_list(n) = "do not read"
            !r_list(n) = "Dtwdy"
          case('dtwdz')
            r_list(n) = "do not read"
            !r_list(n) = "Dtwdz"
          case('extravar1','extravar2', 'extravar3', 'extravar4', 'extravar5')
            r_list(n) = "do not read"
            !r_list(n) = trim(lcase(w_list(n)))
          case Default
            print*, err//trim(r_list(n))//" from file"
            r_list(n) = "do not read"
        end select
      end do
    end subroutine verify_read_control
Call graph
verify_read_control calls lcase
read_file calls verify_read_control
initstate calls read_file
setup_state calls initstate
setup_solver calls setup_state
setup_all calls setup_state
start_run calls setup_solver
main calls start_run