vol_tetrahedron – FEST-3D
vol_tetrahedron Function
11 statements
Source File
private function vol_tetrahedron(p1, p2, p3, p4)
Compute the volume of a tetrahedron, given 4 points which are 1-D arrays Since we know that the determinant is to be evaluated of a 3x3 matrix, we write the expression itself
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:) :: p1
real, intent(in), dimension(:) :: p2
real, intent(in), dimension(:) :: p3
real, intent(in), dimension(:) :: p4
Return Value real
Called by
Contents
Source Code
vol_tetrahedron
Source Code
        function vol_tetrahedron(p1, p2, p3, p4)
            !< Compute the volume of a tetrahedron, given 4 points which
            !< are 1-D arrays
            !< Since we know that the determinant is to be evaluated of
            !< a 3x3 matrix, we write the expression itself
            !-----------------------------------------------------------
            implicit none
            real, dimension(:), intent(in):: p1, p2, p3, p4
            real, dimension(1:3,1:3) :: A
            real :: vol_tetrahedron
            A(:, 1) = p1 - p4
            A(:, 2) = p2 - p4
            A(:, 3) = p3 - p4
            !vol_tetrahedron = A(1,1) * (A(2,2)*A(3,3) - A(2,3)*A(3,2)) + &
            !                  A(1,2) * (A(2,3)*A(3,1) - A(2,1)*A(3,3)) + &
            !                  A(1,3) * (A(2,1)*A(3,2) - A(2,2)*A(3,1))
            vol_tetrahedron = (p4(1) - p1(1))*((p2(2)-p1(2))*(p3(3)-p1(3)) - (p2(3)-p1(3))*(p3(2)-p1(2))) &
                            + (p4(2) - p1(2))*((p2(3)-p1(3))*(p3(1)-p1(1)) - (p2(1)-p1(1))*(p3(3)-p1(3))) &
                            + (p4(3) - p1(3))*((p2(1)-p1(1))*(p3(2)-p1(2)) - (p2(2)-p1(2))*(p3(1)-p1(1)))
            vol_tetrahedron = -vol_tetrahedron / 6.
        end function vol_tetrahedron
Call graph
vol_hexahedron calls vol_tetrahedron
compute_volumes calls vol_hexahedron
compute_geometric_parameters calls compute_volumes
setup_geometry calls compute_geometric_parameters
setup_solver calls setup_geometry
setup_all calls setup_geometry
start_run calls setup_solver
main calls start_run