wall – FEST-3D
wall Subroutine
7 statements
Source File
private subroutine wall(face)
Adiabatic/Isothermal wall boundary condition
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: face
Name of the face at which boundary condition is called
Calls
Called by
Contents
Source Code
wall
Source Code
      subroutine wall(face)
        !< Adiabatic/Isothermal wall boundary condition
        implicit none
        character(len=*), intent(in) :: face
        !< Name of the face at which boundary condition is called
        call copy3(pressure, "symm",  face)
        call temp_based_density(fixed_wall_temperature, face)
        call no_slip(face)
      end subroutine wall
Call graph
wall calls no_slip, temp_based_density, copy3
no_slip calls copy3, set_omega_at_wall
temp_based_density calls copy3
populate_ghost_primitive calls wall
get_total_conservative_residue calls populate_ghost_primitive
get_next_solution calls get_total_conservative_residue
iterate_one_more_time_step calls get_next_solution
main calls iterate_one_more_time_step