write_restart_log – FEST-3D
write_restart_log Subroutine
14 statements
Source File
private subroutine write_restart_log()
call to write log file in the subdirectory "restart". It is useful information while restarting the solver.
Arguments
None
Calls
Called by
Contents
Source Code
write_restart_log
Source Code
    subroutine write_restart_log()
      !< call to write log file in the subdirectory "restart".
      !< It is useful information while restarting the solver.
      implicit none
      open(RESTART_FILE_UNIT, file=restartfile)
      select case (turbulence)
        case ('none')
          write(RESTART_FILE_UNIT, '(A)') 'viscous'
        case('sst','sst2003', 'kkl', 'ke', 'kw', 'sa', 'saBC', 'des-sst')
          write(RESTART_FILE_UNIT, '(A)') trim(turbulence)
        case DEFAULT
          call dmsg(5, 'dump_solution', 'write_restart_log',&
                    'ERROR: Turbulence model not recognised')
      end select
      call write_initial_resnorm()
      close(RESTART_FILE_UNIT)
    end subroutine write_restart_log
Call graph
write_restart_log calls dmsg, write_initial_resnorm
dump_data calls write_restart_log
checkpoint calls dump_data
setup_solver calls checkpoint
iterate_one_more_time_step calls checkpoint
main calls iterate_one_more_time_step, start_run
start_run calls setup_solver