write_time – FEST-3D
write_time Function
16 statements
Source File
private function write_time(time_in_seconds) result(string)
Particular format to write time in output log file
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: time_in_seconds
time to output
Return Value character(len=64)
time as string in particlar format
Called by
Contents
Source Code
write_time
Source Code
        function write_time(time_in_seconds) result(string)
          !< Particular format to write time in output log file
          implicit none
          real, intent(in) :: time_in_seconds
          !< time to output
          character(len=64):: string
          !< time as string in particlar format
          if(time_in_seconds>86400) then
            write(string,'(f0.16,2x,A)') time_in_seconds/86400.,"days"
          elseif(time_in_seconds>3600) then
            write(string,'(f0.16,2x,A)') time_in_seconds/3600.,"Hr."
          elseif(time_in_seconds>60) then
            write(string,'(f0.16,2x,A)') time_in_seconds/60.,"Min."
          elseif(time_in_seconds>0) then
            write(string,'(f0.16,2x,A)') time_in_seconds,"Sec."
          else
            write(string,'(A)') "Not Valid"
          end if
        end function write_time
Call graph
destroy_time calls write_time
destroy_all calls destroy_time
destroy_solver calls destroy_time
finish_run calls destroy_solver
abort_run calls destroy_solver
main calls finish_run