alloc – FEST-3D
alloc Interface
3 statements
Source File
public interface alloc
Calls
Called by
Contents
Module Procedures
alloc_rank1_real alloc_rank2_real alloc_rank3_real alloc_rank4_real alloc_rank5_real alloc_rank6_real alloc_rank1_integer alloc_rank2_integer alloc_rank3_integer
Module Procedures
private subroutine alloc_rank1_real(var, start1, stop1, errmsg)
Allcoate 1-Dimensional array of type: real
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank2_real(var, start1, stop1, start2, stop2, errmsg)
Allcoate 2-Dimensional array of type: real
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:, :), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank3_real(var, start1, stop1, start2, stop2, start3, stop3, errmsg)
Allcoate 3-Dimensional array of type: real
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:, :, :), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
integer, intent(in) :: start3
Starting index of Var array's dimension
integer, intent(in) :: stop3
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank4_real(var, start1, stop1, start2, stop2, start3, stop3, start4, stop4, errmsg)
Allcoate 4-Dimensional array of type: real
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:, :, :, :), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
integer, intent(in) :: start3
Starting index of Var array's dimension
integer, intent(in) :: stop3
Last index of Var array's dimension
integer, intent(in) :: start4
Starting index of Var array's dimension
integer, intent(in) :: stop4
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank5_real(var, start1, stop1, start2, stop2, start3, stop3, start4, stop4, start5, stop5, errmsg)
Allcoate 5-Dimensional array of type: real
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:, :, :, :, :), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
integer, intent(in) :: start3
Starting index of Var array's dimension
integer, intent(in) :: stop3
Last index of Var array's dimension
integer, intent(in) :: start4
Starting index of Var array's dimension
integer, intent(in) :: stop4
Last index of Var array's dimension
integer, intent(in) :: start5
Starting index of Var array's dimension
integer, intent(in) :: stop5
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank6_real(var, start1, stop1, start2, stop2, start3, stop3, start4, stop4, start5, stop5, start6, stop6, errmsg)
Allcoate 6-Dimensional array of type: real
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(:, :, :, :, :,:), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
integer, intent(in) :: start3
Starting index of Var array's dimension
integer, intent(in) :: stop3
Last index of Var array's dimension
integer, intent(in) :: start4
Starting index of Var array's dimension
integer, intent(in) :: stop4
Last index of Var array's dimension
integer, intent(in) :: start5
Starting index of Var array's dimension
integer, intent(in) :: stop5
Last index of Var array's dimension
integer, intent(in) :: start6
Starting index of Var array's dimension
integer, intent(in) :: stop6
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank1_integer(var, start1, stop1, errmsg)
Allcoate 1-Dimensional array of type: integer
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank2_integer(var, start1, stop1, start2, stop2, errmsg)
Allcoate 2-Dimensional array of type: integer
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:, :), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
private subroutine alloc_rank3_integer(var, start1, stop1, start2, stop2, start3, stop3, errmsg)
Allcoate 3-Dimensional array of type: integer
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:, :, :), allocatable :: var
Variable to which memory is allocated
integer, intent(in) :: start1
Starting index of Var array's dimension
integer, intent(in) :: stop1
Last index of Var array's dimension
integer, intent(in) :: start2
Starting index of Var array's dimension
integer, intent(in) :: stop2
Last index of Var array's dimension
integer, intent(in) :: start3
Starting index of Var array's dimension
integer, intent(in) :: stop3
Last index of Var array's dimension
character(len=*), intent(in), optional :: errmsg
Error message to print if mem_stat is not 0(successful)
Call graph
alloc calls alloc_rank2_real, alloc_rank4_real, alloc_rank3_real, alloc_rank2_integer, alloc_rank1_integer, alloc_rank6_real, alloc_rank5_real, alloc_rank3_integer, alloc_rank1_real
destroy_time calls alloc
setup_interface calls alloc
setup_gradients calls alloc
setup_bc calls alloc
setup_scheme calls alloc, setup_interpolant_scheme
allocate_memory calls alloc
setup_state calls alloc
setup_viscosity calls alloc
find_wall_dist calls alloc
setup_wall_dist calls alloc
setup_lusgs calls alloc
setup_update calls alloc, setup_lusgs, setup_plusgs
setupcc calls alloc
setup_time calls alloc
setup_plusgs calls alloc
setup_interpolant_scheme calls alloc
setup_solver calls setup_interface, setup_gradients, setup_bc, setup_scheme, setup_state, setup_viscosity, find_wall_dist, setup_wall_dist, setup_update, setupcc, setup_time, setup_resnorm, write_surfnode
setup_resnorm calls allocate_memory
setup_surface calls allocate_memory
destroy_solver calls destroy_time
finish_run calls destroy_solver
write_surfnode calls setup_surface
start_run calls setup_solver
main calls finish_run, start_run
abort_run calls finish_run