assignment(=) – FEST-3D
assignment(=) Interface
3 statements
Source File
public interface assignment(=)
Calls
Contents
Module Procedures
int4_from_string int8_from_string
Module Procedures
public subroutine int4_from_string(lhs, rhs)
Get integer of kind 4 from the string which might contain either octal or binary number
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(out) :: lhs
character(len=*), intent(in) :: rhs
public subroutine int8_from_string(lhs, rhs)
Get integer of kind 8 from the string which might contain either octal or binary number
Arguments
Type Intent Optional Attributes Name
integer(kind=8), intent(out) :: lhs
character(len=*), intent(in) :: rhs
Call graph
assignment(=) calls int4_from_string, int8_from_string
int4_from_string calls bin2int, oct2int
int8_from_string calls bin2int, oct2int
bin2int calls bin_to_int8, bin_to_int4
oct2int calls oct_to_int8, oct_to_int4