bin2int – FEST-3D
bin2int Interface
3 statements
Source File
public interface bin2int
Calls
Called by
Contents
Module Procedures
bin_to_int4 bin_to_int8
Module Procedures
public subroutine bin_to_int4(r, binstr)
String of binary number converted to integer of kind 4
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(out) :: r
character(len=*) :: binstr
public subroutine bin_to_int8(r, binstr)
String of binary number converted to integer of kind 8
Arguments
Type Intent Optional Attributes Name
integer(kind=8), intent(out) :: r
character(len=*) :: binstr
Call graph
bin2int calls bin_to_int8, bin_to_int4
int4_from_string calls bin2int
int8_from_string calls bin2int
assignment(=) calls int4_from_string, int8_from_string