len – FEST-3D
len Interface
3 statements
Source File
public interface len
Calls
Contents
Module Procedures
intlen reallen
Module Procedures
public function intlen(i) result(l)
Return the "string length of an integer"
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Return Value integer
public function reallen(r) result(l)
Return the "string length of a real"
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: r
Return Value integer
Call graph
len calls intlen, reallen
intlen calls tostr
reallen calls real_to_str
tostr calls real_to_str, int_to_str, bool_to_str