operator(.or.) – FEST-3D
operator(.or.) Interface
3 statements
Source File
public interface operator(.or.)
Calls
Contents
Module Procedures
int4_or_int4 int4_1D_or_int4_1D int4_1D_or_int4 int4_2D_or_int4_2D int4_2D_or_int4 int8_or_int8
Module Procedures
public function int4_or_int4(a, b) result(r)
Bitwise 'OR' over two integer of kind 4
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in) :: a
integer(kind=4), intent(in) :: b
Return Value integer(kind=4)
public function int4_1D_or_int4_1D(a, b) result(r)
Bitwise 'OR' over two 1D integer array of kind 4
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in), dimension(:) :: a
integer(kind=4), intent(in), dimension(:) :: b
Return Value integer(kind=4), dimension(size(a))
public function int4_1D_or_int4(a, b) result(r)
Bitwise 'OR' over one 1D integer array and integer of kind 4
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in), dimension(:) :: a
integer(kind=4), intent(in) :: b
Return Value integer(kind=4), dimension(size(a))
public function int4_2D_or_int4_2D(a, b) result(r)
Bitwise 'OR' over two 2D integer array of kind 4
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in), dimension(:, :) :: a
integer(kind=4), intent(in), dimension(:, :) :: b
Return Value integer(kind=4), dimension(:, :), allocatable
public function int4_2D_or_int4(a, b) result(r)
Bitwise 'OR' over one 2D integer array and integer of kind 4
Arguments
Type Intent Optional Attributes Name
integer(kind=4), intent(in), dimension(:, :) :: a
integer(kind=4), intent(in) :: b
Return Value integer(kind=4), dimension(:, :), allocatable
public function int8_or_int8(a, b) result(r)
Bitwise 'OR' over two integer of kind 8
Arguments
Type Intent Optional Attributes Name
integer(kind=8), intent(in) :: a
integer(kind=8), intent(in) :: b
Return Value integer(kind=8)
Call graph
operator(.or.) calls int4_or_int4, int4_1d_or_int4, int4_2d_or_int4_2d, int4_2d_or_int4, int4_1d_or_int4_1d, int8_or_int8