main – FEST-3D
main Program
12 statements
Source File
Uses
solver
convergence
Main program
Calls
Contents
Source Code
main
Source Code
program main
  !< Main program
  !-------------------------------------------------
  use solver     ,  only: iterate_one_more_time_step
  use solver     ,  only: control
  use convergence,  only: converged
  use solver, only:  start_run
  use solver, only: finish_run
#include "error.inc"
#include "mpi.inc"
!--------Start---------!
  call start_run()
  do while ((control%current_iter <= control%max_iters) .and. (.not. converged(control)) .and. (.not. control%Halt))
     call iterate_one_more_time_step()
  end do
  call finish_run()
!--------Stop---------!
end program main
Call graph
main calls iterate_one_more_time_step, finish_run, converged, start_run
iterate_one_more_time_step calls mpi_bcast, checkpoint, debugcall, find_resnorm, get_next_solution
finish_run calls destroy_solver, mpi_finalize
start_run calls mpi_init, setup_solver
destroy_solver calls debugcall, destroy_time
setup_solver calls checkpoint, debugcall, initmisc, mpi_barrier, setup_geometry, setup_time, setup_gradients, setupcc, setup_state, setup_scheme, find_wall_dist, setup_wall_dist, write_surfnode, read_input_and_controls, setup_interface, setup_bc, setup_resnorm, setup_viscosity, get_process_data, setup_update, read_layout_file, setup_grid
checkpoint calls debugcall, make_dump_dir, purge_dump_dir, dump_data
find_resnorm calls write_resnorm, collect_resnorm_from_all_blocks, assemble_resnom_at_each_process, get_absolute_resnorm, get_relative_resnorm
get_next_solution calls update_with_lusgs, compute_time_step, update_with, update_with_plusgs, get_total_conservative_residue